Repository containerd/cri, pull requests merged in 2018-04, with the labels that each got.

#711 Drop libapparmor dependency from build docs
  .travis.yml
  README.md
  contrib/ansible/tasks/bootstrap_ubuntu.yaml
  docs/installation.md
  hack/install/install-deps.sh
  test/build-utils.sh
Labels: lgtm, size/S

#714 adds a new flag to enable TLS support (insecure for now)
  pkg/config/config.go
  pkg/server/streaming.go
Labels: lgtm, size/S

#715 Upgrade the tarball version in ansible.
  contrib/ansible/tasks/binaries.yaml
  contrib/ansible/vars/vars.yaml
Labels: lgtm, size/XS

#716 Update cri test to include RunAsGroup test.
  hack/utils.sh
Labels: lgtm, size/XS

#713 switches from not CA signed to self CA signed for streaming TLS
  pkg/server/streaming.go
Labels: lgtm, size/M

#717 Enable TLS streaming in all the setup.
  cluster/gce/cloud-init/master.yaml
  cluster/gce/cloud-init/node.yaml
  contrib/ansible/cri-containerd.yaml
  docs/config.md
  test/e2e_node/init.yaml
Labels: lgtm, size/S

#720 Update containerd once before release.
  vendor.conf
  vendor/github.com/containerd/containerd/LICENSE
  vendor/github.com/containerd/containerd/LICENSE.docs
  vendor/github.com/containerd/containerd/README.md
  vendor/github.com/containerd/containerd/oci/spec_opts.go
  vendor/github.com/containerd/containerd/oci/spec_opts_unix.go
  vendor/github.com/containerd/containerd/oci/spec_opts_windows.go
  vendor/github.com/containerd/containerd/snapshotter_default_unix.go
  vendor/github.com/containerd/containerd/sys/socket_unix.go
Labels: lgtm, size/L

#719 Update readme on how to configure cri plugin
  README.md
Labels: lgtm, size/XS

#724 Add cni config template
  cluster/gce/cloud-init/master.yaml
  cluster/gce/cloud-init/node.yaml
  cluster/gce/cni.template
  cluster/gce/env
  docs/config.md
  pkg/config/config.go
  pkg/server/testing/fake_cni_plugin.go
  pkg/server/update_runtime_config.go
  pkg/server/update_runtime_config_test.go
  vendor.conf
  vendor/github.com/containerd/containerd/cmd/ctr/commands/run/run.go
  vendor/github.com/containerd/containerd/cmd/ctr/commands/run/run_unix.go
  vendor/github.com/containerd/containerd/oci/spec_opts.go
  vendor/github.com/containerd/containerd/oci/spec_opts_unix.go
  vendor/github.com/containerd/containerd/vendor.conf
  vendor/github.com/containerd/containerd/version/version.go
Labels: lgtm, size/L

#725 Fix resolver race
  pkg/containerd/resolver/resolver.go
Labels: lgtm, size/M

#691 Getting rid of nsenter and socat
  .travis.yml
  README.md
  contrib/ansible/tasks/bootstrap_centos.yaml
  contrib/ansible/tasks/bootstrap_ubuntu.yaml
  pkg/server/sandbox_portforward.go
  pkg/store/sandbox/netns.go
Labels: lgtm, size/L

#728 Minor cleanup of comment in ansible
  contrib/ansible/tasks/bootstrap_ubuntu.yaml
Labels: lgtm, size/XS

#727 Support symlink layer in image import.
  pkg/containerd/importer/importer.go
Labels: lgtm, size/M

#729 Add socat back.
  .travis.yml
  README.md
  contrib/ansible/tasks/bootstrap_centos.yaml
  contrib/ansible/tasks/bootstrap_ubuntu.yaml
  pkg/server/sandbox_portforward.go
Labels: lgtm, size/M

#731 Add release instruction to make the release process written down.
  docs/release.md
Labels: lgtm, size/S

#735 start tracking golang updates for 1.10.x
  .travis.yml
Labels: lgtm, size/XS

#739 Fix portforward for host network.
  hack/utils.sh
  pkg/server/sandbox_portforward.go
Labels: lgtm, size/S

#743 Fix sandbox stop race condition.
  pkg/server/sandbox_stop.go
Labels: lgtm, size/S

#745 Try using preloaded containerd if no version is specified.
  cluster/gce/configure.sh
Labels: lgtm, size/M

#748 Add `unix://` prefix for socket addresses used by CRI remote client.
  README.md
  cluster/gce/env
  contrib/ansible/cri-containerd.yaml
  docs/crictl.md
  hack/install/install-critools.sh
  hack/test-utils.sh
  hack/utils.sh
  integration/test_utils.go
Labels: lgtm, size/S

#750 Download containerd binaries from official release.
  docs/release.md
  hack/install/install-deps.sh
  hack/release.sh
Labels: lgtm, size/M

#751 Fix tarball ownership and containerd binary path for containerd.
  hack/release.sh
Labels: cherrypick, lgtm, size/XS

#752 Cherry pick #750 and #751
  docs/release.md
  hack/install/install-deps.sh
  hack/release.sh
Labels: lgtm, size/M

#756 Update cri-tools to fix `crictl logs` output.
  hack/utils.sh
Labels: cherrypick, lgtm

#757 Update cri-tools to fix `crictl logs` output.
  hack/utils.sh
Labels: cherrypick, lgtm, size/XS

#754 os.Unmount: do not consult mountinfo
  pkg/os/os.go
  pkg/os/testing/fake_os.go
  pkg/server/sandbox_run.go
  pkg/store/sandbox/netns.go
Labels: lgtm, size/M
