Repository containerd/cri, pull requests merged in 2018-02, with the labels that each got.

#608 adds lower case containerd to the list of authors
  hack/boilerplate/boilerplate.py
Labels: lgtm, size/XS

#609 Support reopening container log.
  hack/versions
  pkg/ioutil/writer_group.go
  pkg/ioutil/writer_group_test.go
  pkg/server/container_attach.go
  pkg/server/container_log_reopen.go
  pkg/server/container_start.go
  pkg/server/io/container_io.go
  pkg/server/restart.go
Labels: lgtm, size/L

#612 Add initial wait for health-monitor and use pkill -x.
  cluster/health-monitor.sh
  hack/test-utils.sh
  integration/test_utils.go
Labels: lgtm, size/S

#611 Do not block on stream server close.
  cluster/gce/cloud-init/master.yaml
  cluster/gce/cloud-init/node.yaml
  pkg/server/service.go
Labels: lgtm, priority/P0, size/S

#600 removes hack versions; splits update vendor into optional sort and sync operations
  Makefile
  README.md
  docs/crictl.md
  hack/install-deps.sh
  hack/sort-vendor.sh
  hack/sync-vendor.sh
  hack/test-utils.sh
  hack/utils.sh
  hack/versions
Labels: lgtm, size/L

#617 Fix a potential panic
  pkg/store/container/container.go
  pkg/store/sandbox/sandbox.go
  pkg/store/util.go
Labels: lgtm, size/M

#620 Update critools to b184f9aefe60a4441330e615ee20634ee26474fb.
  hack/utils.sh
Labels: lgtm, size/XS

#622 Update support matrix.
  README.md
Labels: size/XS

#625 Enable container log rotation.
  cluster/gce/env
Labels: lgtm, size/XS

#621 adds go 1.10 to ci test
  .travis.yml
Labels: lgtm, size/M

#618 Add generic restart test
  .travis.yml
  hack/install-deps.sh
  integration/restart_test.go
  integration/test_utils.go
  vendor.conf
  vendor/github.com/containerd/containerd/api/events/container.pb.go
  vendor/github.com/containerd/containerd/api/services/events/v1/events.pb.go
  vendor/github.com/containerd/containerd/cio/io_unix.go
  vendor/github.com/containerd/containerd/client.go
  vendor/github.com/containerd/containerd/cmd/containerd/command/main.go
  vendor/github.com/containerd/containerd/linux/runtime.go
  vendor/github.com/containerd/containerd/mount/mount.go
  vendor/github.com/containerd/containerd/mount/temp.go
  vendor/github.com/containerd/containerd/mount/temp_unix.go
  vendor/github.com/containerd/containerd/mount/temp_unsupported.go
  vendor/github.com/containerd/containerd/task.go
  vendor/github.com/containerd/containerd/vendor.conf
Labels: lgtm, size/XL

#629 moving to go1.10 only
  .travis.yml
  README.md
Labels: lgtm, size/M
