Repository containerd/cri, pull requests merged in 2018-10, with the labels that each got.

#935 corrects syntax error in Makefile
  Makefile
Labels: lgtm, size/XS

#937 cni result: add a debug message
  pkg/server/sandbox_run.go
Labels: lgtm, size/S

#938 Update kubernetes to v1.12.0.
  integration/addition_gids_test.go
  integration/container_log_test.go
  integration/container_stats_test.go
  integration/container_update_resources_test.go
  integration/containerd_image_test.go
  integration/duplicate_name_test.go
  integration/image_load_test.go
  integration/imagefs_info_test.go
  integration/pod_hostname_env_test.go
  integration/restart_test.go
  integration/sandbox_clean_remove_test.go
  integration/test_utils.go
  integration/truncindex_test.go
  integration/volume_copy_up_test.go
  vendor.conf
  vendor/k8s.io/api/core/v1/generated.pb.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go
  vendor/k8s.io/client-go/rest/request.go
  vendor/k8s.io/kubernetes/README.md
  vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  vendor/k8s.io/kubernetes/pkg/apis/core/zz_generated.deepcopy.go
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/services.go
  vendor/k8s.io/kubernetes/pkg/kubelet/remote/remote_image.go
  vendor/k8s.io/kubernetes/pkg/kubelet/remote/remote_runtime.go
Labels: lgtm, size/XXL

#939 Cherrypick #938 to release/1.2
  integration/addition_gids_test.go
  integration/container_log_test.go
  integration/container_stats_test.go
  integration/container_update_resources_test.go
  integration/containerd_image_test.go
  integration/duplicate_name_test.go
  integration/image_load_test.go
  integration/imagefs_info_test.go
  integration/pod_hostname_env_test.go
  integration/restart_test.go
  integration/sandbox_clean_remove_test.go
  integration/test_utils.go
  integration/truncindex_test.go
  integration/volume_copy_up_test.go
  vendor.conf
  vendor/k8s.io/api/core/v1/generated.pb.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go
  vendor/k8s.io/client-go/rest/request.go
  vendor/k8s.io/kubernetes/README.md
  vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  vendor/k8s.io/kubernetes/pkg/apis/core/zz_generated.deepcopy.go
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/services.go
  vendor/k8s.io/kubernetes/pkg/kubelet/remote/remote_image.go
  vendor/k8s.io/kubernetes/pkg/kubelet/remote/remote_runtime.go
Labels: cherrypick, lgtm, size/XXL

#944 Use authorizer
  pkg/server/image_pull.go
  vendor.conf
  vendor/github.com/Microsoft/hcsshim/hnsendpoint.go
  vendor/github.com/containerd/containerd/archive/compression/compression.go
  vendor/github.com/containerd/containerd/cmd/ctr/commands/resolver.go
  vendor/github.com/containerd/containerd/cmd/ctr/commands/run/run_unix.go
  vendor/github.com/containerd/containerd/cmd/ctr/commands/signals.go
  vendor/github.com/containerd/containerd/cmd/ctr/commands/tasks/kill.go
  vendor/github.com/containerd/containerd/container_opts.go
  vendor/github.com/containerd/containerd/images/archive/importer.go
  vendor/github.com/containerd/containerd/images/image.go
  vendor/github.com/containerd/containerd/metadata/content.go
  vendor/github.com/containerd/containerd/oci/spec_opts.go
  vendor/github.com/containerd/containerd/remotes/docker/authorizer.go
  vendor/github.com/containerd/containerd/remotes/docker/resolver.go
  vendor/github.com/containerd/containerd/runtime/v2/binary.go
  vendor/github.com/containerd/containerd/runtime/v2/shim/shim.go
  vendor/github.com/containerd/containerd/runtime/v2/shim/shim_windows.go
  vendor/github.com/containerd/containerd/runtime/v2/shim/util_windows.go
  vendor/github.com/containerd/containerd/signal_map_linux.go
  vendor/github.com/containerd/containerd/signal_map_unix.go
  vendor/github.com/containerd/containerd/signal_map_windows.go
  vendor/github.com/containerd/containerd/signals.go
  vendor/github.com/containerd/containerd/vendor.conf
  vendor/github.com/containerd/containerd/version/version.go
Labels: lgtm, size/XXL

#941 test: Fix compile error with go1.10.2
  integration/image_load_test.go
Labels: lgtm, needs-ok-to-test, size/XS

#943 Support runtime specific configurations.
  docs/config.md
  pkg/config/config.go
  pkg/server/container_create.go
  pkg/server/container_start.go
  pkg/server/container_status.go
  pkg/server/helpers.go
  pkg/server/helpers_test.go
  pkg/server/sandbox_run.go
  pkg/server/sandbox_status.go
Labels: lgtm, size/L

#947 Cherrypick #943 to release/1.2
  docs/config.md
  pkg/config/config.go
  pkg/server/container_create.go
  pkg/server/container_start.go
  pkg/server/container_status.go
  pkg/server/helpers.go
  pkg/server/helpers_test.go
  pkg/server/sandbox_run.go
  pkg/server/sandbox_status.go
Labels: cherrypick, lgtm, size/L

#949 Fix ip leakage
  integration/restart_test.go
  integration/sandbox_clean_remove_test.go
  integration/test_utils.go
  pkg/server/container_status.go
  pkg/server/sandbox_status.go
  pkg/server/sandbox_stop.go
  pkg/store/sandbox/netns.go
  vendor.conf
  vendor/github.com/containerd/go-cni/cni.go
Labels: lgtm, priority/P0, size/L

#951 Cherrypick #949 release 1.2
  integration/restart_test.go
  integration/sandbox_clean_remove_test.go
  integration/test_utils.go
  pkg/server/container_status.go
  pkg/server/sandbox_status.go
  pkg/server/sandbox_stop.go
  pkg/store/sandbox/netns.go
  vendor.conf
  vendor/github.com/containerd/go-cni/cni.go
Labels: cherrypick, lgtm, size/L

#953 refactor: setup network after get Sandbox runtime
  pkg/server/sandbox_run.go
Labels: lgtm, size/S

#952 Cherrypick #949 release 1.0
  integration/restart_test.go
  integration/sandbox_clean_remove_test.go
  integration/test_utils.go
  pkg/server/container_status.go
  pkg/server/sandbox_status.go
  pkg/server/sandbox_stop.go
  pkg/server/service.go
  pkg/server/status.go
  pkg/server/testing/fake_cni_plugin.go
  pkg/server/update_runtime_config.go
  pkg/store/sandbox/netns.go
  vendor.conf
  vendor/github.com/containerd/go-cni/README.md
  vendor/github.com/containerd/go-cni/cni.go
  vendor/github.com/containerd/go-cni/opts.go
Labels: cherrypick, lgtm, size/L

#957 link to new icon location
  README.md
  contrib/ansible/README.md
Labels: lgtm, size/XS

#958 Cherrypick #950 release 1.2
  integration/sandbox_clean_remove_test.go
  integration/test_utils.go
  pkg/netns/netns.go
  pkg/server/helpers.go
  pkg/server/restart.go
  pkg/server/sandbox_portforward.go
  pkg/server/sandbox_remove.go
  pkg/server/sandbox_run.go
  pkg/server/sandbox_status.go
  pkg/server/sandbox_stop.go
  pkg/store/sandbox/netns.go
  pkg/store/sandbox/sandbox.go
Labels: lgtm, size/L

#959 Use commit as version.
  Makefile
Labels: lgtm, size/XS

#961 removes authconfig from info log
  pkg/server/instrumented_service.go
Labels: lgtm, size/XS

#964 cherry-pick #961 for 1.0 removes authconfig from info log
  pkg/server/instrumented_service.go
Labels: lgtm, size/XS
