Repository containerd/cri, pull requests merged in 2018-09, with the labels that each got.

#886 stream: can use user certificates
  docs/config.md
  pkg/config/config.go
  pkg/server/streaming.go
  pkg/server/streaming_test.go
Labels: lgtm, size/L

#895 Add HOSTNAME to env by default for pod containers
  pkg/server/container_create.go
Labels: lgtm, size/XS

#897 [release/1.11] Cherrypick: add HOSTNAME to env
  pkg/server/container_create.go
Labels: lgtm, size/XS

#892 Sort volume mount.
  pkg/server/container_create.go
  pkg/server/container_create_test.go
  pkg/server/helpers.go
  pkg/server/helpers_test.go
Labels: lgtm, size/L

#901 Fix hostname env.
  pkg/os/os.go
  pkg/os/testing/fake_os.go
  pkg/server/container_create.go
  pkg/server/container_create_test.go
  pkg/server/helpers.go
Labels: lgtm, size/M

#908 Update kubernetes to v1.12.0-beta.1.
  vendor.conf
  vendor/golang.org/x/oauth2/LICENSE
  vendor/golang.org/x/oauth2/README.md
  vendor/golang.org/x/oauth2/client_appengine.go
  vendor/golang.org/x/oauth2/internal/oauth2.go
  vendor/golang.org/x/oauth2/internal/token.go
  vendor/golang.org/x/oauth2/internal/transport.go
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/token.go
  vendor/golang.org/x/oauth2/transport.go
  vendor/k8s.io/api/core/v1/generated.pb.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/generated.proto
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types_swagger_doc_generated.go
  vendor/k8s.io/apimachinery/pkg/util/net/interface.go
  vendor/k8s.io/apimachinery/pkg/util/validation/validation.go
  vendor/k8s.io/client-go/rest/config.go
  vendor/k8s.io/client-go/rest/token_source.go
  vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  vendor/k8s.io/kubernetes/pkg/apis/core/zz_generated.deepcopy.go
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/runtime/v1alpha2/api.pb.go
Labels: lgtm, size/XXL

#905 Cherrypick #901 to release/1.0
  pkg/os/os.go
  pkg/os/testing/fake_os.go
  pkg/server/container_create.go
  pkg/server/container_create_test.go
  pkg/server/helpers.go
Labels: cherrypick, lgtm, size/M

#906 Cherrypick #901 to release/1.11
  pkg/os/os.go
  pkg/os/testing/fake_os.go
  pkg/server/container_create.go
  pkg/server/container_create_test.go
  pkg/server/helpers.go
Labels: cherrypick, lgtm, size/M

#912 Add hostname env integration test.
  integration/pod_hostname_env_test.go
  integration/test_utils.go
Labels: lgtm, size/L

#918 Show runtime handler in sandbox debug info.
  pkg/server/container_status.go
  pkg/server/sandbox_run.go
  pkg/server/sandbox_status.go
  pkg/store/sandbox/metadata.go
Labels: lgtm, size/M

#919 Update cri-tools to 98eea54af789ae13edce79cba101fb9ac8e7b241.
  README.md
  docs/crictl.md
  docs/installation.md
  docs/proposal.md
  docs/testing.md
  hack/utils.sh
Labels: lgtm, size/S

#920 The indent is wrong.
  docs/config.md
Labels: lgtm, size/XS

#921 Turn off `--fail-swap-on` in node e2e test.
  hack/test-e2e-node.sh
Labels: lgtm, size/S

#923 Vendor in runtime-spec & runtime-tools from github.com/opencontainers
  vendor.conf
  vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
  vendor/github.com/opencontainers/runtime-tools/README.md
  vendor/github.com/opencontainers/runtime-tools/generate/config.go
  vendor/github.com/opencontainers/runtime-tools/generate/generate.go
Labels: lgtm, size/M

#927 Fix readiness check in test utils.
  hack/test-utils.sh
Labels: lgtm, size/S

#929 Cherrypick #928 release/1.2
  hack/utils.sh
Labels: cherrypick, lgtm, size/XS

#926 Better external image handling
  integration/containerd_image_test.go
  integration/restart_test.go
  integration/test_utils.go
  pkg/server/events.go
  pkg/server/helpers.go
  pkg/server/image_load.go
  pkg/server/image_pull.go
  pkg/server/restart.go
  pkg/server/service.go
Labels: lgtm, priority/P0, size/L

#933 Cherrypick #926 release/1.2
  integration/containerd_image_test.go
  integration/restart_test.go
  integration/test_utils.go
  pkg/server/events.go
  pkg/server/helpers.go
  pkg/server/image_load.go
  pkg/server/image_pull.go
  pkg/server/restart.go
  pkg/server/service.go
Labels: cherrypick, lgtm, size/L
