Repository containerd/cri, pull requests merged in 2018-03, with the labels that each got.

#631 Expose cri version for CRI plugin.
  cri.go
Labels: lgtm, size/XS

#632 tests: Use path found to containerd.
  hack/test-utils.sh
Labels: lgtm, size/XS

#637 adds allways to ensure there is a version even if no tag
  .travis.yml
  Makefile
Labels: lgtm, size/XS

#635 fix travis golang issue
  .travis.yml
Labels: size/XS

#636 Only overwrite when legacy options are specified.
  cmd/cri-containerd/options/options.go
Labels: size/XS

#640 documents load image
  docs/crictl.md
Labels: lgtm, size/M

#643 Fix a potential panic.
  pkg/server/events.go
Labels: lgtm, size/XS

#639 Remove standalone mode
  .travis.yml
  Makefile
  cluster/gce/cloud-init/master.yaml
  cluster/gce/cloud-init/node.yaml
  cluster/gce/configure.sh
  cluster/gce/env
  cluster/health-monitor.sh
  cmd/cri-containerd/cri_containerd.go
  cmd/cri-containerd/options/options.go
  cmd/cri-containerd/options/registry.go
  cmd/ctrcri/ctrcri.go
  contrib/ansible/README.md
  contrib/ansible/cri-containerd.yaml
  contrib/ansible/tasks/binaries.yaml
  contrib/ansible/vars/vars.yaml
  contrib/systemd-units/cri-containerd.service
  cri.go
  hack/install-deps.sh
  hack/release.sh
  hack/test-cri.sh
  hack/test-e2e-node.sh
  hack/test-integration.sh
  hack/test-utils.sh
  integration/container_stats_test.go
  integration/test_utils.go
  pkg/config/config.go
  pkg/server/service.go
  pkg/server/service_test.go
  test/build.sh
  test/configure.sh
  test/e2e_node/benchmark-config.yaml
  test/e2e_node/image-config.yaml
  test/e2e_node/init.yaml
Labels: size/XXL

#641 Require ansible 2.4+.
  contrib/ansible/README.md
Labels: lgtm, size/XS

#648 Fix cleanup context.
  pkg/containerd/importer/importer.go
  pkg/containerd/util/util.go
  pkg/server/container_create.go
  pkg/server/container_execsync.go
  pkg/server/container_start.go
  pkg/server/container_update_resources.go
  pkg/server/sandbox_run.go
Labels: lgtm, size/M

#650 Handles 401 in resolver.
  pkg/containerd/resolver/resolver.go
Labels: lgtm, size/XS

#644 [in-process-integration] Start switching to direct function call
  cri.go
  integration/test_utils.go
  pkg/constants/constants.go
  pkg/server/container_create.go
  pkg/server/events.go
  pkg/server/instrumented_service.go
  pkg/server/sandbox_portforward.go
  pkg/server/service.go
  pkg/server/snapshots.go
  pkg/server/streaming.go
  vendor/github.com/containerd/containerd/client.go
  vendor/github.com/containerd/containerd/grpc_services.go
  vendor/github.com/containerd/containerd/lease.go
  vendor/github.com/containerd/containerd/local_services.go
Labels: size/XL

#558 Report containerd version instead of cri-containerd version.
  pkg/server/version.go
Labels: size/S

#654 pkg/store: use a sync.Once to synchronize channel close
  pkg/store/util.go
Labels: lgtm, size/S

#651 Add document about registry configuration
  docs/registry.md
Labels: lgtm, size/M

#630 Add CLI package for `ctr` to use.
  cli/cli.go
Labels: lgtm, size/M

#628 Handle containerd event reliably
  pkg/os/os.go
  pkg/server/events.go
  pkg/server/events_test.go
  pkg/server/helpers.go
Labels: size/L

#670 Enable promisc mode because Kubernetes network model needs it.
  hack/install-deps.sh
Labels: lgtm, size/XS

#669 Cleanup event backoff.
  pkg/server/events.go
  pkg/server/events_test.go
Labels: lgtm, size/M

#663 Moving to use go-cni library from containerd
  pkg/server/helpers.go
  pkg/server/sandbox_run.go
  pkg/server/sandbox_run_test.go
  pkg/server/sandbox_stop.go
  pkg/server/service.go
  pkg/server/status.go
  pkg/server/testing/fake_cni_plugin.go
  vendor.conf
  vendor/github.com/containerd/go-cni/LICENSE
  vendor/github.com/containerd/go-cni/README.md
  vendor/github.com/containerd/go-cni/cni.go
  vendor/github.com/containerd/go-cni/errors.go
  vendor/github.com/containerd/go-cni/helper.go
  vendor/github.com/containerd/go-cni/namespace.go
  vendor/github.com/containerd/go-cni/namespace_opts.go
  vendor/github.com/containerd/go-cni/opts.go
  vendor/github.com/containerd/go-cni/result.go
  vendor/github.com/containerd/go-cni/testutils.go
  vendor/github.com/containerd/go-cni/types.go
  vendor/github.com/containerd/go-cni/vendor.conf
  vendor/github.com/cri-o/ocicni/README.md
  vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/types.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/util.go
  vendor/github.com/fsnotify/fsnotify/LICENSE
  vendor/github.com/fsnotify/fsnotify/README.md
  vendor/github.com/fsnotify/fsnotify/fen.go
  vendor/github.com/fsnotify/fsnotify/fsnotify.go
  vendor/github.com/fsnotify/fsnotify/inotify.go
  vendor/github.com/fsnotify/fsnotify/inotify_poller.go
  vendor/github.com/fsnotify/fsnotify/kqueue.go
  vendor/github.com/fsnotify/fsnotify/open_mode_bsd.go
  vendor/github.com/fsnotify/fsnotify/open_mode_darwin.go
  vendor/github.com/fsnotify/fsnotify/windows.go
Labels: lgtm, size/XXL

#667 docs update for cri-containerd to cri move
  README.md
  contrib/ansible/README.md
  docs/architecture.md
  docs/cri.png
  docs/crictl.md
  docs/installation.md
  docs/registry.md
  docs/testing.md
Labels: size/L

#674 Removing DAD config and updating plugins to v0.7.0
  pkg/config/config.go
  pkg/server/helpers.go
  pkg/server/sandbox_run.go
  vendor.conf
  vendor/github.com/containernetworking/plugins/README.md
  vendor/github.com/containernetworking/plugins/pkg/ns/ns.go
  vendor/github.com/containernetworking/plugins/pkg/ns/ns_linux.go
  vendor/github.com/containernetworking/plugins/pkg/ns/ns_unspecified.go
  vendor/k8s.io/kubernetes/pkg/util/sysctl/sysctl.go
Labels: lgtm, size/XL

#675 Fix containerd repo test.
  test/build-containerd.sh
  test/configure.sh
  test/e2e_node/image-config-containerd.yaml
Labels: lgtm, size/S

#678 Use `github.com/pkg/errors`
  cli/cli.go
  integration/container_stats_test.go
  integration/imagefs_info_test.go
  integration/test_utils.go
  pkg/client/client.go
  pkg/containerd/resolver/resolver.go
  pkg/registrar/registrar.go
  pkg/server/container_attach.go
  pkg/server/container_create.go
  pkg/server/container_exec.go
  pkg/server/container_execsync.go
  pkg/server/container_log_reopen.go
  pkg/server/container_remove.go
  pkg/server/container_start.go
  pkg/server/container_stats.go
  pkg/server/container_stats_list.go
  pkg/server/container_status.go
  pkg/server/container_stop.go
  pkg/server/container_update_resources.go
  pkg/server/events.go
  pkg/server/helpers.go
  pkg/server/image_load.go
  pkg/server/image_pull.go
  pkg/server/image_remove.go
  pkg/server/image_status.go
  pkg/server/io/logger.go
  pkg/server/restart.go
  pkg/server/sandbox_portforward.go
  pkg/server/sandbox_remove.go
  pkg/server/sandbox_run.go
  pkg/server/sandbox_status.go
  pkg/server/sandbox_stop.go
  pkg/server/service.go
  pkg/server/snapshots.go
  pkg/server/streaming.go
  pkg/store/container/metadata.go
  pkg/store/container/status.go
  pkg/store/sandbox/metadata.go
  pkg/store/sandbox/netns.go
  pkg/util/deep_copy.go
Labels: lgtm, size/XL

#680 Only set deploy dir.
  test/containerd/build.sh
Labels: lgtm, size/XS

#683 Rename all variables to remove "cricontainerd".
  cli/cli.go
  cri.go
  hack/update-proto.sh
  integration/image_load_test.go
  integration/test_utils.go
  integration/volume_copy_up_test.go
  pkg/api/v1/api.pb.go
  pkg/api/v1/api.proto
  pkg/client/client.go
  pkg/config/config.go
  pkg/server/container_attach.go
  pkg/server/container_create.go
  pkg/server/container_create_test.go
  pkg/server/container_exec.go
  pkg/server/container_execsync.go
  pkg/server/container_list.go
  pkg/server/container_list_test.go
  pkg/server/container_log_reopen.go
  pkg/server/container_remove.go
  pkg/server/container_start.go
  pkg/server/container_stats.go
  pkg/server/container_stats_list.go
  pkg/server/container_status.go
  pkg/server/container_status_test.go
  pkg/server/container_stop.go
  pkg/server/container_stop_test.go
  pkg/server/container_update_resources.go
  pkg/server/helpers.go
  pkg/server/image_list.go
  pkg/server/image_list_test.go
  pkg/server/image_load.go
  pkg/server/image_pull.go
  pkg/server/image_remove.go
  pkg/server/image_status.go
  pkg/server/image_status_test.go
  pkg/server/imagefs_info.go
  pkg/server/imagefs_info_test.go
  pkg/server/instrumented_service.go
  pkg/server/restart.go
  pkg/server/sandbox_list.go
  pkg/server/sandbox_list_test.go
  pkg/server/sandbox_portforward.go
  pkg/server/sandbox_remove.go
  pkg/server/sandbox_run.go
  pkg/server/sandbox_run_test.go
  pkg/server/sandbox_status.go
  pkg/server/sandbox_stop.go
  pkg/server/sandbox_stop_test.go
  pkg/server/service.go
  pkg/server/service_test.go
  pkg/server/status.go
  pkg/server/streaming.go
  pkg/server/update_runtime_config.go
  pkg/server/version.go
Labels: lgtm, size/L

#684 Fix for kube-up.sh and update several documments.
  Makefile
  cluster/gce/configure.sh
  cluster/gce/env
  docs/crictl.md
  docs/kube-up.md
  hack/release.sh
Labels: lgtm, size/M

#682 Update README.d and graphs.
  README.md
  docs/architecture.png
  docs/cri.png
Labels: lgtm, size/M

#685 Update cri-tools and build critest into release tarball again.
  hack/install/install-critools.sh
  hack/install/install-deps.sh
  hack/test-cri.sh
  hack/utils.sh
Labels: lgtm, size/S

#657 [WIP]config: Allow to define trusted runtime
  hack/test-utils.sh
  pkg/annotations/annotations.go
  pkg/config/config.go
  pkg/server/container_create.go
  pkg/server/helpers.go
  pkg/server/helpers_test.go
  pkg/server/sandbox_run.go
  pkg/server/sandbox_run_test.go
Labels: lgtm, size/L

#689 Remove omitempty from config json.
  pkg/config/config.go
Labels: lgtm, size/M

#690 Bump pause container to multi-arch gcr.io/google-containers/pause:3.1
  contrib/ansible/cri-containerd.yaml
  integration/test_utils.go
  pkg/config/config.go
Labels: lgtm, size/XS

#681 adds tls certificate to tls config
  hack/utils.sh
  pkg/server/streaming.go
Labels: lgtm, size/L

#694 Make const private.
  pkg/server/streaming.go
Labels: lgtm, size/S

#688 Address comments for privileged runtime code.
  hack/test-utils.sh
  pkg/annotations/annotations.go
  pkg/config/config.go
  pkg/server/container_create.go
  pkg/server/container_status.go
  pkg/server/helpers.go
  pkg/server/helpers_test.go
  pkg/server/sandbox_run.go
  pkg/server/sandbox_run_test.go
  pkg/server/sandbox_status.go
Labels: lgtm, size/L

#695 Add a document for cri plugin config
  docs/config.md
Labels: lgtm, size/M

#696 Update documents.
  README.md
  docs/cri.png
  docs/installation.md
  docs/registry.md
  docs/testing.md
Labels: lgtm, size/L

#697 adds volatile state directory to the fs plan for cntrs/pods/fifo
  cri.go
  docs/config.md
  docs/crictl.md
  pkg/config/config.go
  pkg/os/os.go
  pkg/os/testing/fake_os.go
  pkg/server/container_create.go
  pkg/server/container_create_test.go
  pkg/server/container_execsync.go
  pkg/server/container_remove.go
  pkg/server/helpers.go
  pkg/server/restart.go
  pkg/server/sandbox_remove.go
  pkg/server/sandbox_run.go
  pkg/server/sandbox_run_test.go
  pkg/server/sandbox_stop.go
  pkg/server/service_test.go
  pkg/store/sandbox/netns.go
Labels: lgtm, size/L

#700 Use pause image from new source.
  contrib/ansible/cri-containerd.yaml
  docs/config.md
  docs/crictl.md
  integration/test_utils.go
  pkg/config/config.go
Labels: lgtm, size/S

#701 Fix event monitor panic.
  pkg/server/events.go
Labels: lgtm, size/S

#704 Use systemd service cgroup and oom score adj.
  cluster/gce/cloud-init/master.yaml
  cluster/gce/cloud-init/node.yaml
  cluster/gce/env
  contrib/ansible/cri-containerd.yaml
  test/e2e_node/init.yaml
Labels: lgtm, size/M

#706 fully specify --container-runtime-endpoint flag
  docs/installation.md
Labels: lgtm, size/XS

#707 Fix a log output.
  pkg/server/sandbox_portforward.go
Labels: lgtm, size/XS

#710 Add RunAsGroup support.
  pkg/server/container_create.go
  pkg/server/sandbox_run.go
  vendor.conf
  vendor/github.com/containerd/containerd/archive/tar_windows.go
  vendor/github.com/containerd/containerd/contrib/seccomp/seccomp_default.go
  vendor/github.com/containerd/containerd/image.go
  vendor/github.com/containerd/containerd/linux/shim/client/client.go
  vendor/github.com/containerd/containerd/oci/spec_opts_unix.go
  vendor/github.com/containerd/containerd/sys/socket_unix.go
  vendor/github.com/containerd/containerd/vendor.conf
Labels: lgtm, size/L
