Repository containerd/cri, pull requests merged in 2018-06, with the labels that each got.

#776 Disable TLS streaming to work with new kubelet streaming proxy.
  cluster/gce/configure.sh
  contrib/ansible/cri-containerd.yaml
Labels: lgtm, size/S

#801 FIx ctr cri timeout.
  cli/cli.go
  integration/test_utils.go
  pkg/client/client.go
Labels: lgtm, size/S

#803 Select ipv4 first if there is one.
  pkg/server/sandbox_run.go
  pkg/server/sandbox_run_test.go
Labels: lgtm, size/M

#802 Remove unused files.
  test/containerd/env
  test/containerd/image-config.yaml
  test/e2e_node/benchmark-config.yaml
  test/e2e_node/image-config.yaml
  test/env
Labels: kind/cleanup, kind/test, lgtm

#804 Use pod ip instead of localhost in pod netns for portforward.
  pkg/server/sandbox_portforward.go
Labels: size/M

#808 Erase ambient capabilities.
  pkg/server/container_create.go
  pkg/server/container_create_test.go
Labels: lgtm, size/XS

#807 Log task exit event.
  pkg/server/events.go
Labels: lgtm, size/XS

#810 Revert "Use pod ip instead of localhost in pod netns for portforward."
  pkg/server/sandbox_portforward.go
Labels: lgtm, size/M

#811 Fix empty volume ownership.
  integration/images/volume-ownership/Dockerfile
  integration/images/volume-ownership/Makefile
  integration/volume_copy_up_test.go
  pkg/containerd/opts/container.go
Labels: kind/bug, lgtm, size/L

#815 Support `Cmd` for sandbox container.
  pkg/server/sandbox_run.go
  pkg/server/sandbox_run_test.go
Labels: lgtm, size/XS

#816 Fix double /dev/shm mount.
  pkg/server/container_create.go
  pkg/server/sandbox_run.go
Labels: lgtm, size/S

#818 Fix double /dev/shm mount.
  pkg/server/container_create.go
  pkg/server/sandbox_run.go
Labels: cherrypick, size/S

#761 Add log max size
  docs/config.md
  integration/container_log_test.go
  integration/container_update_resources_test.go
  integration/test_utils.go
  pkg/config/config.go
  pkg/ioutil/write_closer.go
  pkg/ioutil/write_closer_test.go
  pkg/server/container_log_reopen.go
  pkg/server/container_start.go
  pkg/server/io/logger.go
  pkg/server/io/logger_test.go
  pkg/server/restart.go
Labels: lgtm, size/XL

#824 Make max container log line size configurable through cloud init.
  cluster/gce/configure.sh
Labels: lgtm, size/XS

#823 Update crictl to v1.11.0.
  hack/utils.sh
Labels: lgtm, size/XS

#821 Fix snapshotter nil panic.
  pkg/server/service.go
Labels: lgtm, size/XS

#826 Fix snapshotter nil panic.
  pkg/server/service.go
Labels: cherrypick, lgtm, size/XS

#820 Update github.com/opencontainers/runtime-tools to v0.6.0
  pkg/server/container_create.go
  pkg/server/container_create_test.go
  pkg/server/container_execsync.go
  pkg/server/container_update_resources.go
  pkg/server/sandbox_run.go
  vendor.conf
  vendor/github.com/opencontainers/runtime-tools/README.md
  vendor/github.com/opencontainers/runtime-tools/error/error.go
  vendor/github.com/opencontainers/runtime-tools/filepath/abs.go
  vendor/github.com/opencontainers/runtime-tools/filepath/ancestor.go
  vendor/github.com/opencontainers/runtime-tools/filepath/clean.go
  vendor/github.com/opencontainers/runtime-tools/filepath/doc.go
  vendor/github.com/opencontainers/runtime-tools/filepath/join.go
  vendor/github.com/opencontainers/runtime-tools/filepath/separator.go
  vendor/github.com/opencontainers/runtime-tools/generate/config.go
  vendor/github.com/opencontainers/runtime-tools/generate/generate.go
  vendor/github.com/opencontainers/runtime-tools/generate/seccomp/seccomp_default.go
  vendor/github.com/opencontainers/runtime-tools/generate/seccomp/seccomp_default_linux.go
  vendor/github.com/opencontainers/runtime-tools/generate/seccomp/seccomp_default_unsupported.go
  vendor/github.com/opencontainers/runtime-tools/generate/spec.go
  vendor/github.com/opencontainers/runtime-tools/specerror/bundle.go
  vendor/github.com/opencontainers/runtime-tools/specerror/config-linux.go
  vendor/github.com/opencontainers/runtime-tools/specerror/config-windows.go
  vendor/github.com/opencontainers/runtime-tools/specerror/config.go
  vendor/github.com/opencontainers/runtime-tools/specerror/error.go
  vendor/github.com/opencontainers/runtime-tools/specerror/runtime-linux.go
  vendor/github.com/opencontainers/runtime-tools/specerror/runtime.go
  vendor/github.com/opencontainers/runtime-tools/validate/validate.go
  vendor/github.com/opencontainers/runtime-tools/validate/validate_linux.go
  vendor/github.com/opencontainers/runtime-tools/validate/validate_unsupported.go
  vendor/github.com/xeipuuv/gojsonpointer/LICENSE-APACHE-2.0.txt
  vendor/github.com/xeipuuv/gojsonpointer/README.md
  vendor/github.com/xeipuuv/gojsonpointer/pointer.go
  vendor/github.com/xeipuuv/gojsonreference/LICENSE-APACHE-2.0.txt
  vendor/github.com/xeipuuv/gojsonreference/README.md
  vendor/github.com/xeipuuv/gojsonreference/reference.go
  vendor/github.com/xeipuuv/gojsonschema/LICENSE-APACHE-2.0.txt
  vendor/github.com/xeipuuv/gojsonschema/README.md
  vendor/github.com/xeipuuv/gojsonschema/errors.go
  vendor/github.com/xeipuuv/gojsonschema/format_checkers.go
  vendor/github.com/xeipuuv/gojsonschema/internalLog.go
  vendor/github.com/xeipuuv/gojsonschema/jsonContext.go
  vendor/github.com/xeipuuv/gojsonschema/jsonLoader.go
  vendor/github.com/xeipuuv/gojsonschema/locales.go
  vendor/github.com/xeipuuv/gojsonschema/result.go
  vendor/github.com/xeipuuv/gojsonschema/schema.go
  vendor/github.com/xeipuuv/gojsonschema/schemaPool.go
  vendor/github.com/xeipuuv/gojsonschema/schemaReferencePool.go
  vendor/github.com/xeipuuv/gojsonschema/schemaType.go
  vendor/github.com/xeipuuv/gojsonschema/subSchema.go
  vendor/github.com/xeipuuv/gojsonschema/types.go
  vendor/github.com/xeipuuv/gojsonschema/utils.go
  vendor/github.com/xeipuuv/gojsonschema/validation.go
Labels: lgtm, size/XXL

#825 Change to keep in sync with latest cni config
  pkg/server/service.go
  pkg/server/status.go
  pkg/server/testing/fake_cni_plugin.go
  pkg/server/update_runtime_config.go
  vendor.conf
  vendor/github.com/containerd/go-cni/README.md
  vendor/github.com/containerd/go-cni/cni.go
  vendor/github.com/containerd/go-cni/opts.go
Labels: lgtm, size/L

#829 Set stream server to serve on localhost on GCE.
  cluster/gce/configure.sh
Labels: lgtm, size/XS

#828 Fix the link to the GCE getting-started guide
  docs/kube-up.md
Labels: lgtm, size/XS

#831 Fix another link.
  docs/kube-up.md
Labels: lgtm, size/XS

#832 Remove crictl on GCE for all cases.
  cluster/gce/configure.sh
Labels: lgtm, size/XS
