Repository containerd/cri, pull requests merged in 2018-08, with the labels that each got.

#872 [cherry-pick] support no_pivot option for runc
  docs/config.md
  pkg/config/config.go
  pkg/server/container_start.go
  pkg/server/sandbox_run.go
Labels: cherrypick, lgtm, size/S

#873 Verify selinux level format
  pkg/server/helpers.go
  pkg/server/helpers_selinux_test.go
  vendor.conf
  vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
  vendor/github.com/opencontainers/selinux/go-selinux/xattrs.go
Labels: lgtm, size/XL

#877 Cherry pick #873 into release-1.11
  pkg/server/helpers.go
  pkg/server/helpers_selinux_test.go
  vendor.conf
  vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
  vendor/github.com/opencontainers/selinux/go-selinux/xattrs.go
Labels: cherrypick, lgtm, size/XL

#876 Cherry pick #873 into release-1.0
  pkg/server/helpers.go
  pkg/server/helpers_selinux_test.go
  vendor.conf
  vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
  vendor/github.com/opencontainers/selinux/go-selinux/xattrs.go
Labels: lgtm, size/XL

#885 Fix an issue that container/sandbox can't be stopped.
  pkg/server/container_stop.go
  pkg/server/sandbox_stop.go
Labels: kind/bug, lgtm, size/M

#888 Cherrypick #885 to release/1.11
  pkg/server/container_stop.go
  pkg/server/sandbox_stop.go
Labels: cherrypick, lgtm, size/M

#887 Cherrypick #885 to release/1.0
  pkg/server/container_stop.go
  pkg/server/sandbox_stop.go
Labels: cherrypick, lgtm, size/M

#890 Update go-cni to 6d7b509a054a3cb1c35ed1865d4fde2f0cb547cd.
  vendor.conf
  vendor/github.com/containerd/go-cni/opts.go
Labels: lgtm, size/M
