Repository containerd/cri, pull requests merged in 2018-11, with the labels that each got.

#966 Cherrypick #959 release 1.2
  Makefile
Labels: cherrypick, lgtm, size/XS

#965 update the slack information
  README.md
Labels: lgtm, size/XS

#967 Update support metrics to include containerd 1.2.
  README.md
Labels: lgtm, size/XS

#969 Update code for golang 1.11 gofmt.
  pkg/server/helpers.go
Labels: lgtm, size/S

#974 Remove invalid TODO comment.
  pkg/server/events.go
Labels: lgtm, size/XS

#973 Use the `ID` field of `TaskExit` event.
  pkg/server/events.go
Labels: lgtm, size/S

#975 Cherrypick #973 release 1.2
  pkg/server/events.go
Labels: cherrypick, lgtm, size/S

#954 adds golang 1.11.x to build
  .travis.yml
  integration/container_update_resources_test.go
Labels: lgtm, size/M

#976 Remove the unused `health-monitor.sh`.
  cluster/health-monitor.sh
Labels: kind/cleanup, lgtm, size/M

#977 Only install necessary tools.
  .travis.yml
Labels: lgtm, size/XS

#980 adds cni results to verbose pod info
  pkg/server/sandbox_run.go
  pkg/server/sandbox_status.go
  pkg/store/sandbox/metadata.go
Labels: lgtm, size/S
