Repository containerd/cri, pull requests merged in 2018-05, with the labels that each got.

#763 Explicitly set `rw` for privileged container.
  pkg/server/container_create.go
  pkg/server/container_create_test.go
Labels: cherrypick, lgtm, size/S

#764 Explicitly set `rw` for privileged container.
  pkg/server/container_create.go
  pkg/server/container_create_test.go
Labels: lgtm, size/S

#766 Fix workingset memory calculation.
  pkg/server/container_stats_list.go
  pkg/server/container_stats_list_test.go
Labels: cherrypick, lgtm, size/M

#767 Cherrypick #766 into release/1.0 branch.
  pkg/server/container_stats_list.go
  pkg/server/container_stats_list_test.go
Labels: cherrypick, lgtm, size/M

#771 Upgrade cri-tools to v1.0.0-beta.1
  hack/utils.sh
Labels: cherrypick, lgtm

#769 Minor typo
  pkg/server/sandbox_run_test.go
Labels: lgtm, size/XS

#773 Update containerd to 01a0741488487779a95035cd85504589034d2e91.
  vendor.conf
  vendor/github.com/containerd/containerd/client.go
  vendor/github.com/containerd/containerd/cmd/ctr/commands/events/events.go
  vendor/github.com/containerd/containerd/cmd/ctr/commands/tasks/list.go
  vendor/github.com/containerd/containerd/vendor.conf
  vendor/github.com/containerd/containerd/version/version.go
Labels: lgtm, size/M

#775 use public logos for a while vs remote github logos not in this repo
  README.md
Labels: cherrypick, size/XS

#778 Cherrypick #775
  README.md
Labels: cherrypick, lgtm, size/XS

#779 Another logo fix.
  contrib/ansible/README.md
Labels: cherrypick, lgtm

#758 Use crictl installed in kube-up.sh
  cluster/gce/cloud-init/master.yaml
  cluster/gce/cloud-init/node.yaml
  cluster/gce/configure.sh
  cluster/health-monitor.sh
Labels: lgtm, size/M

#781 Fix kube-container-runtime-monitor.
  cluster/gce/cloud-init/master.yaml
  cluster/gce/cloud-init/node.yaml
Labels: lgtm, size/XS

#784 Bump continuity to fix copy files > 2^32 bytes
  vendor.conf
  vendor/github.com/containerd/continuity/fs/copy.go
  vendor/github.com/containerd/continuity/fs/copy_linux.go
  vendor/github.com/containerd/continuity/sysx/xattr_linux.go
  vendor/github.com/containerd/continuity/sysx/xattr_linux_386.go
  vendor/github.com/containerd/continuity/sysx/xattr_linux_amd64.go
  vendor/github.com/containerd/continuity/sysx/xattr_linux_arm.go
  vendor/github.com/containerd/continuity/sysx/xattr_linux_arm64.go
  vendor/github.com/containerd/continuity/sysx/xattr_linux_ppc64.go
  vendor/github.com/containerd/continuity/sysx/xattr_linux_ppc64le.go
  vendor/github.com/containerd/continuity/sysx/xattr_linux_s390x.go
Labels: lgtm, size/XL

#786 Remove useless error-check in createImageReference
  pkg/server/image_pull.go
Labels: lgtm, size/XS

#788 Update cni.template
  cluster/gce/cni.template
Labels: lgtm, size/S

#789 Make DEPLOY_PATH configurable.
  test/containerd/build.sh
Labels: cherrypick, lgtm

#792 Make DEPLOY_PATH configurable.
  test/containerd/build.sh
Labels: cherrypick, lgtm

#793 Port docker resolver fix #2364.
  pkg/containerd/resolver/fetcher.go
  pkg/containerd/resolver/fetcher_test.go
Labels: cherrypick, lgtm, size/L

#795 Port docker resolver fix #2364.
  pkg/containerd/resolver/fetcher.go
  pkg/containerd/resolver/fetcher_test.go
Labels: cherrypick, lgtm

#794 Generate fatal error when cri plugin fail to start.
  pkg/server/events.go
  pkg/server/service.go
Labels: cherrypick, lgtm, size/M

#797 Generate fatal error when cri plugin fail to start.
  pkg/server/events.go
  pkg/server/service.go
Labels: lgtm, size/M
