Repository containerd/cri, pull requests merged in 2018-12, with the labels that each got.

#984 filter events for non k8s.io namespaces
  pkg/server/events.go
Labels: lgtm, size/XS

#987 Cherrypick #984 release 1.2
  pkg/server/events.go
Labels: lgtm, size/XS

#988 Cherrypick #984 release 1.0
  pkg/server/events.go
Labels: cherrypick, lgtm, size/XS

#989 Test that CRI plugin should not see image in other namespaces.
  integration/containerd_image_test.go
Labels: kind/test, lgtm, size/M

#992 fix spelling error: contaner -> container
  pkg/server/container_create_test.go
Labels: lgtm, ok-to-test, size/XS

#991 Remove container lifecycle image dependency
  integration/container_without_image_ref_test.go
  pkg/server/container_create.go
  pkg/server/container_status.go
  pkg/server/container_stop.go
  pkg/store/container/container_test.go
  pkg/store/container/metadata.go
Labels: kind/bug, lgtm, size/L

#993 Fix some typo errors
  pkg/server/image_pull.go
Labels: lgtm, ok-to-test, size/XS

#997 Temporary fix for golang regression #29241.
  hack/test-cri.sh
Labels: lgtm, size/XS

#999 Cherrypick #997 release 1.2
  hack/test-cri.sh
Labels: cherrypick, lgtm, size/XS

#998 Cherrypick #997 release 1.0
  hack/test-cri.sh
Labels: cherrypick, lgtm

#996 Cherrypick #991 release 1.2
  integration/container_without_image_ref_test.go
  pkg/server/container_create.go
  pkg/server/container_status.go
  pkg/server/container_stop.go
  pkg/store/container/container_test.go
  pkg/store/container/metadata.go
Labels: cherrypick, lgtm, size/L

#1004 Install libseccomp2 based on debian version
  test/build-utils.sh
Labels: lgtm, size/S

#1006 Cherrypick #1004 release 1.0
  test/build-utils.sh
Labels: cherrypick, lgtm, size/S

#1005 Cherrypick #1004 release 1.2
  test/build-utils.sh
Labels: cherrypick, lgtm, size/S

#1003 Revert "Temporary fix for golang regression #29241."
  hack/test-cri.sh
Labels: lgtm, size/XS

#1007 Revert #999 release 1.2
  hack/test-cri.sh
Labels: lgtm, size/XS

#1008 Revert #998 release 1.0
  hack/test-cri.sh
Labels: lgtm, size/XS

#1013 Fix return error message
  pkg/server/restart.go
  pkg/server/sandbox_stop.go
Labels: lgtm, ok-to-test, size/XS
