Repository containerd/cri, pull requests merged in 2018-07, with the labels that each got.

#839 Backport #761 to release/1.0
  docs/config.md
  hack/verify-lint.sh
  integration/container_log_test.go
  integration/container_update_resources_test.go
  integration/test_utils.go
  pkg/config/config.go
  pkg/ioutil/write_closer.go
  pkg/ioutil/write_closer_test.go
  pkg/server/container_log_reopen.go
  pkg/server/container_start.go
  pkg/server/io/logger.go
  pkg/server/io/logger_test.go
  pkg/server/restart.go
Labels: lgtm, size/XL

#841 Add missing vendor back.
  vendor/github.com/docker/docker/contrib/README.md
  vendor/github.com/docker/docker/contrib/nnp-test/nnp-test.c
  vendor/github.com/docker/docker/contrib/syscall-test/acct.c
  vendor/github.com/docker/docker/contrib/syscall-test/exit32.s
  vendor/github.com/docker/docker/contrib/syscall-test/ns.c
  vendor/github.com/docker/docker/contrib/syscall-test/raw.c
  vendor/github.com/docker/docker/contrib/syscall-test/setgid.c
  vendor/github.com/docker/docker/contrib/syscall-test/setuid.c
  vendor/github.com/docker/docker/contrib/syscall-test/socket.c
  vendor/github.com/docker/docker/contrib/syscall-test/userns.c
  vendor/golang.org/x/crypto/otr/libotr_test_helper.c
  vendor/golang.org/x/crypto/otr/otr.go
  vendor/golang.org/x/crypto/otr/smp.go
  vendor/golang.org/x/crypto/ssh/test/doc.go
  vendor/golang.org/x/crypto/ssh/test/sshd_test_pw.c
  vendor/golang.org/x/sys/windows/svc/event.go
  vendor/golang.org/x/sys/windows/svc/go12.c
  vendor/golang.org/x/sys/windows/svc/go12.go
  vendor/golang.org/x/sys/windows/svc/go13.go
  vendor/golang.org/x/sys/windows/svc/security.go
  vendor/golang.org/x/sys/windows/svc/service.go
  vendor/golang.org/x/sys/windows/svc/sys_386.s
  vendor/golang.org/x/sys/windows/svc/sys_amd64.s
  vendor/k8s.io/kubernetes/build/README.md
  vendor/k8s.io/kubernetes/build/pause/orphan.c
  vendor/k8s.io/kubernetes/build/pause/pause.c
Labels: lgtm, size/XXL

#843 Use `--no-overwrite-dir` in installation doc.
  docs/installation.md
  hack/release.sh
Labels: kind/docs, lgtm, size/XS

#845 Cherrypick #843 to release/1.11
  docs/installation.md
  hack/release.sh
Labels: cherrypick, lgtm, size/XS

#849 Replace stringid call with simple random reader
  cmd/containerd/containerd.go
  cmd/ctr/main.go
  pkg/util/id.go
  vendor/github.com/docker/docker/pkg/stringid/README.md
  vendor/github.com/docker/docker/pkg/stringid/stringid.go
Labels: lgtm, size/L

#846 Cherrypick #843 to release/1.0
  docs/installation.md
  hack/release.sh
Labels: cherrypick, lgtm, size/XS

#851 support no_pivot option for runc
  docs/config.md
  pkg/config/config.go
  pkg/server/container_start.go
  pkg/server/sandbox_run.go
Labels: lgtm, size/S

#854 [cherry-pick]support no_pivot option for runc
  docs/config.md
  pkg/config/config.go
  pkg/server/container_start.go
  pkg/server/sandbox_run.go
Labels: cherrypick, size/S

#858 Serve streaming on localhost by default to match k8s 1.11 default.
  cluster/gce/configure.sh
  docs/config.md
  pkg/config/config.go
Labels: lgtm, size/XS

#860 Cherrypick #858 to release/1.11.
  cluster/gce/configure.sh
  docs/config.md
  pkg/config/config.go
Labels: cherrypick, lgtm, size/XS

#857 sandbox: separate host accessing workload and privileged
  pkg/server/sandbox_run.go
  pkg/server/sandbox_run_test.go
Labels: lgtm, size/M

#864 Unpack image during import.
  hack/verify-lint.sh
  pkg/containerd/importer/importer.go
  pkg/server/image_load.go
Labels: lgtm, size/M

#867 Cherrypick the lint fix.
  hack/verify-lint.sh
Labels: cherrypick, lgtm, size/XS

#868 Cherrypick #867 to release/1.0 branch.
  hack/verify-lint.sh
Labels: cherrypick, lgtm, size/XS

#866 sandbox: separate host accessing workload and privileged
  pkg/server/sandbox_run.go
  pkg/server/sandbox_run_test.go
Labels: cherrypick, lgtm, size/M

#869 Support netd in GCE bootstrap.
  cluster/gce/configure.sh
Labels: lgtm, size/S

#870 Cherrypick #869 into release/1.11
  cluster/gce/configure.sh
Labels: cherrypick, lgtm, size/S
