Repository containerd/cri, pull requests merged in 2019-08, with the labels that each got.

#1209 Fix proc mount support.
  docs/config.md
  pkg/config/config.go
  pkg/server/container_create.go
Labels: lgtm, size/M

#1217 Print warning message for deprecated options.
  cri.go
  docs/config.md
  pkg/server/container_start.go
  pkg/server/helpers.go
  pkg/server/helpers_test.go
  pkg/server/sandbox_run.go
Labels: lgtm, size/M

#1218 Add test for disable_proc_mount.
  pkg/server/container_create_test.go
Labels: cherrypick-needed, lgtm, size/S

#1219 Rename the test binary to containerd-test.
  hack/test-integration.sh
  hack/test-utils.sh
  integration/test_utils.go
Labels: lgtm, size/S

#1216 Cherrypick #1209 release/1.2
  docs/config.md
  pkg/config/config.go
  pkg/server/container_create.go
  pkg/server/container_create_test.go
Labels: cherrypick, lgtm, size/M

#1220 Do not deprecate no_pivot yet.
  cri.go
  docs/config.md
  pkg/config/config.go
Labels: lgtm, size/S

#1224 Infer systemd cgroup
  pkg/server/container_create.go
  pkg/server/container_create_test.go
  pkg/server/helpers.go
  pkg/server/helpers_test.go
  pkg/server/sandbox_run.go
  pkg/server/sandbox_run_test.go
Labels: lgtm, size/M

#1226 Use golangci-lint
  Makefile
  hack/verify-lint.sh
  integration/test_utils.go
Labels: lgtm, size/M

#1223 Update support metrics to reflect 1.11 EOL.
  README.md
Labels: lgtm, size/S

#1221 Switch to containerd/log package
  pkg/containerd/opts/container.go
  pkg/containerd/opts/spec.go
  pkg/log/log.go
  pkg/server/container_attach.go
  pkg/server/container_create.go
  pkg/server/container_create_test.go
  pkg/server/container_execsync.go
  pkg/server/container_remove.go
  pkg/server/container_start.go
  pkg/server/container_stop.go
  pkg/server/container_update_resources.go
  pkg/server/container_update_resources_test.go
  pkg/server/helpers_test.go
  pkg/server/image_pull.go
  pkg/server/image_status.go
  pkg/server/instrumented_service.go
  pkg/server/restart.go
  pkg/server/sandbox_portforward.go
  pkg/server/sandbox_remove.go
  pkg/server/sandbox_run.go
  pkg/server/sandbox_stop.go
  pkg/server/status.go
  pkg/server/streaming.go
  pkg/server/update_runtime_config.go
Labels: lgtm, size/L

#1200 Assign ImageSpec User if SecurityContext is not set
  pkg/server/container_create.go
  pkg/server/container_create_test.go
  pkg/server/sandbox_run.go
Labels: lgtm, size/L

#1225 Add flag to overload default privileged host device behaviour
  docs/config.md
  pkg/config/config.go
  pkg/server/container_create.go
  pkg/server/container_create_test.go
Labels: ok-to-test, size/L

#1228 Improve vendor.conf
  hack/sort-vendor.sh
  vendor.conf
  vendor/github.com/containerd/cgroups/cgroup.go
  vendor/github.com/containerd/cgroups/metrics.pb.go
  vendor/github.com/containerd/cgroups/metrics.proto
  vendor/github.com/containerd/cgroups/utils.go
  vendor/github.com/davecgh/go-spew/LICENSE
  vendor/github.com/davecgh/go-spew/README.md
  vendor/github.com/davecgh/go-spew/spew/bypass.go
  vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
  vendor/github.com/davecgh/go-spew/spew/common.go
  vendor/github.com/davecgh/go-spew/spew/dump.go
  vendor/github.com/davecgh/go-spew/spew/format.go
  vendor/github.com/google/gofuzz/fuzz.go
  vendor/github.com/stretchr/testify/README.md
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/golang.org/x/oauth2/LICENSE
  vendor/golang.org/x/oauth2/README.md
  vendor/golang.org/x/oauth2/client_appengine.go
  vendor/golang.org/x/oauth2/go.mod
  vendor/golang.org/x/oauth2/internal/client_appengine.go
  vendor/golang.org/x/oauth2/internal/doc.go
  vendor/golang.org/x/oauth2/internal/oauth2.go
  vendor/golang.org/x/oauth2/internal/token.go
  vendor/golang.org/x/oauth2/internal/transport.go
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/token.go
  vendor/golang.org/x/oauth2/transport.go
Labels: size/XXL

#1231 Consider endpoint path when checking default host.
  pkg/server/image_pull.go
  pkg/server/image_pull_test.go
Labels: lgtm, size/M

#1232 Remove extra roundtrip for checking schema1.
  pkg/server/image_pull.go
Labels: lgtm, size/S

#1234 Update containerd to fix panic caused by race condition.
  vendor.conf
  vendor/github.com/containerd/containerd/namespaces/ttrpc.go
  vendor/github.com/containerd/containerd/oci/spec_opts_linux.go
Labels: lgtm, size/S

#1230 Fix unnecessary https trial in release/1.2.
  pkg/server/image_pull.go
Labels: lgtm, size/S

#1233 allow non-mutual TLS
  docs/registry.md
  pkg/server/image_pull.go
Labels: lgtm, size/M

#1235 Add wildcard mirror support.
  docs/registry.md
  pkg/server/image_pull.go
  pkg/server/image_pull_test.go
Labels: lgtm, size/L

#1238 Update cni and go-cni to the v0.7.1 release
  pkg/server/sandbox_run.go
  pkg/server/sandbox_stop.go
  pkg/server/testing/fake_cni_plugin.go
  vendor.conf
  vendor/github.com/containerd/go-cni/README.md
  vendor/github.com/containerd/go-cni/cni.go
  vendor/github.com/containerd/go-cni/helper.go
  vendor/github.com/containerd/go-cni/namespace.go
  vendor/github.com/containerd/go-cni/opts.go
  vendor/github.com/containerd/go-cni/result.go
  vendor/github.com/containerd/go-cni/vendor.conf
  vendor/github.com/containernetworking/cni/README.md
  vendor/github.com/containernetworking/cni/libcni/api.go
  vendor/github.com/containernetworking/cni/libcni/conf.go
  vendor/github.com/containernetworking/cni/pkg/invoke/args.go
  vendor/github.com/containernetworking/cni/pkg/invoke/delegate.go
  vendor/github.com/containernetworking/cni/pkg/invoke/exec.go
  vendor/github.com/containernetworking/cni/pkg/invoke/os_unix.go
  vendor/github.com/containernetworking/cni/pkg/invoke/raw_exec.go
  vendor/github.com/containernetworking/cni/pkg/types/020/types.go
  vendor/github.com/containernetworking/cni/pkg/types/current/types.go
  vendor/github.com/containernetworking/cni/pkg/types/types.go
  vendor/github.com/containernetworking/cni/pkg/version/plugin.go
  vendor/github.com/containernetworking/cni/pkg/version/version.go
Labels: lgtm, size/XL

#1237 Update cni plugins to v0.7.6.
  vendor.conf
Labels: lgtm, size/XS

#1240 Fix apparmor for privileged.
  pkg/server/container_create.go
  pkg/server/container_create_test.go
Labels: cherrypick-needed, lgtm, size/S

#1241 Cherrypick #1240 release 1.2
  pkg/server/container_create.go
  pkg/server/container_create_test.go
Labels: lgtm, size/S

#1242 Explicitly import runtime v2 in the test containerd binary.
  cmd/containerd/containerd.go
Labels: lgtm, size/XS

#1244 Support CNI DNS capabilities.
  pkg/server/helpers.go
  pkg/server/sandbox_run.go
  pkg/server/sandbox_stop.go
  vendor.conf
  vendor/github.com/containerd/go-cni/namespace_opts.go
  vendor/github.com/containerd/go-cni/types.go
Labels: lgtm, size/L

#1250 fix: support empty auth config for anonymous registry
  pkg/server/image_pull.go
  pkg/server/image_pull_test.go
Labels: lgtm, ok-to-test, size/XS

#1251 Add TaskMax=infinity in the systemd unit.
  cluster/gce/cloud-init/master.yaml
  cluster/gce/cloud-init/node.yaml
  contrib/systemd-units/containerd.service
  test/e2e_node/init.yaml
Labels: lgtm, size/XS

#1253 [release/1.3] fix: support empty auth config for anonymous registry
  pkg/server/image_pull.go
  pkg/server/image_pull_test.go
Labels: ok-to-test, size/XS

#1254 [release/1.2] fix: support empty auth config for anonymous registry
  pkg/server/image_pull.go
  pkg/server/image_pull_test.go
Labels: lgtm, ok-to-test, size/XS

#1255 FDQN is a typo, and we don't support trailing dot in FQDN.
  docs/registry.md
  pkg/config/config.go
Labels: lgtm, size/XS
