Repository containerd/cri, pull requests merged in 2019-07, with the labels that each got.

#1190 Update dependency containerd/cgroups
  vendor.conf
  vendor/github.com/containerd/cgroups/cgroup.go
  vendor/github.com/containerd/cgroups/metrics.pb.go
  vendor/github.com/containerd/cgroups/metrics.proto
  vendor/github.com/containerd/cgroups/utils.go
Labels: lgtm, ok-to-test, size/XL

#1194 Correcting typo
  docs/registry.md
Labels: ok-to-test, size/XS

#1177 Return gRPC errors from instrumentedService
  pkg/server/instrumented_service.go
Labels: lgtm, size/M

#1193 [release/1.2 backport] Fix runc and critools version in release.
  hack/install/install-critools.sh
  hack/install/install-runc.sh
Labels: lgtm, ok-to-test, size/XS

#1192 [release/1.0 backport] bump libseccomp-golang v0.9.1
  vendor.conf
  vendor/github.com/seccomp/libseccomp-golang/README
  vendor/github.com/seccomp/libseccomp-golang/seccomp.go
  vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go
Labels: lgtm, ok-to-test, size/L

#1191 [release/1.2 backport] bump libseccomp-golang v0.9.1
  vendor.conf
  vendor/github.com/seccomp/libseccomp-golang/README
  vendor/github.com/seccomp/libseccomp-golang/seccomp.go
  vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go
Labels: lgtm, ok-to-test, size/L

#1176 move up to golang 1.12.x
  .travis.yml
Labels: size/XS

#1173 synching up a bit with containerd Makefile
  Makefile
  cri.go
Labels: size/L

#1203 Update containerd for config backward compatibility.
  vendor.conf
  vendor/github.com/containerd/containerd/cmd/containerd/command/config.go
  vendor/github.com/containerd/containerd/cmd/containerd/command/config_linux.go
  vendor/github.com/containerd/containerd/cmd/containerd/command/config_unsupported.go
  vendor/github.com/containerd/containerd/cmd/containerd/command/config_windows.go
  vendor/github.com/containerd/containerd/remotes/docker/authorizer.go
  vendor/github.com/containerd/containerd/remotes/docker/resolver.go
Labels: lgtm, size/M

#1188 Update docs to v2 config
  docs/config.md
Labels: lgtm, ok-to-test, size/M

#1206 Add containerd font art.
  Makefile
Labels: lgtm, size/XS

#1205 Remove `noSnat`
  cluster/gce/cni.template
Labels: lgtm, size/XS

#1204 Fix ctr readiness check in test.
  hack/test-utils.sh
Labels: lgtm, size/XS

#1202 Do not cache image handler.
  pkg/server/container_create.go
  pkg/server/helpers.go
  pkg/server/sandbox_run.go
  pkg/store/image/image.go
Labels: cherrypick, lgtm, size/S

#1187 Add option to register on TCP server
  docs/config.md
  pkg/config/config.go
  pkg/server/service.go
Labels: lgtm, needs-ok-to-test, size/S

#1152 Return gRPC codes.DeadlineExceeded for all timeout operations
  pkg/server/container_execsync.go
  pkg/server/container_stop.go
  pkg/server/container_stop_test.go
  pkg/server/sandbox_stop.go
  pkg/server/sandbox_stop_test.go
Labels: lgtm, size/M

#1207 Move context cancel into defer.
  pkg/server/container_stop.go
Labels: lgtm, size/XS

#1211 Add max concurrent downloads support.
  docs/config.md
  pkg/config/config.go
  pkg/server/image_pull.go
Labels: lgtm, size/XS

#1210 Cherrypick #1202 release/1.2
  pkg/server/container_create.go
  pkg/server/helpers.go
  pkg/server/sandbox_run.go
  pkg/store/image/image.go
Labels: lgtm, size/S

#1212 Return actual error when fetching the bandwidth info from annotation fails
  pkg/server/sandbox_run.go
Labels: lgtm, ok-to-test, size/XS
