Repository containerd/cri, pull requests merged in 2019-10, with the labels that each got.

#1312 Explicitly specify trusty in travis.
  .appveyor.yml
  .golangci.yml
  .travis.yml
  Makefile
  integration/main_test.go
Labels: cherrypick-needed, size/S

#1313 [release/1.2] Update based on default xenial distro.
  .travis.yml
Labels: cherrypick, size/XS

#1314 [release/1.3] configure golangci-lint and update based on default xenial distro.
  .travis.yml
  Makefile
Labels: cherrypick, size/S

#1319 Fix containerd build, use `libbtrfs-dev` when available.
  test/build-utils.sh
Labels: size/XS

#1321 [release/1.2] Fix containerd build, use `libbtrfs-dev` when available.
  test/build-utils.sh
Labels: cherrypick, lgtm, size/XS

#1322 [release/1.3] Fix containerd build, use `libbtrfs-dev` when available.
  test/build-utils.sh
Labels: cherrypick, lgtm, size/XS

#1320 [release/1.0] Fix containerd build, use `libbtrfs-dev` when available.
  .travis.yml
  test/build-utils.sh
Labels: cherrypick, lgtm, size/S

#1318 Containerd version updated for kubernetes ansible example.
  contrib/ansible/vars/vars.yaml
Labels: lgtm, ok-to-test, size/XS

#1323 logrus supports trace level now.
  cri.go
Labels: size/XS

#1324 Avoid O_NONBLOCK on stdout in the windows test.
  test/windows/runner.sh
Labels: lgtm, size/XS

#1326 [WCOW] Add container compute stats support.
  pkg/server/container_stats_list_windows.go
  vendor.conf
  vendor/github.com/Microsoft/hcsshim/cmd/containerd-shim-runhcs-v1/stats/doc.go
  vendor/github.com/Microsoft/hcsshim/cmd/containerd-shim-runhcs-v1/stats/stats.pb.go
  vendor/github.com/Microsoft/hcsshim/cmd/containerd-shim-runhcs-v1/stats/stats.proto
  vendor/github.com/Microsoft/hcsshim/go.mod
  vendor/github.com/Microsoft/hcsshim/hcn/hcnpolicy.go
  vendor/github.com/Microsoft/hcsshim/internal/cow/cow.go
  vendor/github.com/Microsoft/hcsshim/internal/hcs/system.go
  vendor/github.com/Microsoft/hcsshim/internal/hns/hnspolicy.go
  vendor/github.com/Microsoft/hcsshim/internal/schema2/memory_2.go
  vendor/github.com/Microsoft/hcsshim/internal/schema2/memory_information_for_vm.go
  vendor/github.com/Microsoft/hcsshim/internal/schema2/memory_stats.go
  vendor/github.com/Microsoft/hcsshim/internal/schema2/processor_stats.go
  vendor/github.com/Microsoft/hcsshim/internal/schema2/properties.go
  vendor/github.com/Microsoft/hcsshim/internal/schema2/property_query.go
  vendor/github.com/Microsoft/hcsshim/internal/schema2/property_type.go
  vendor/github.com/Microsoft/hcsshim/internal/schema2/statistics.go
  vendor/github.com/Microsoft/hcsshim/internal/schema2/storage_stats.go
  vendor/github.com/Microsoft/hcsshim/internal/schema2/vm_memory.go
  vendor/github.com/Microsoft/hcsshim/internal/wclayer/expandscratchsize.go
  vendor/github.com/Microsoft/hcsshim/internal/wclayer/wclayer.go
  vendor/github.com/Microsoft/hcsshim/internal/wclayer/zsyscall_windows.go
  vendor/github.com/Microsoft/hcsshim/osversion/osversion_windows.go
  vendor/github.com/Microsoft/hcsshim/osversion/windowsbuilds.go
Labels: lgtm, size/XXL

#1329 Update support metrics.
  README.md
Labels: lgtm, size/S

#1328 Use `http` for localhost and 127.0.0.1 by default.
  pkg/server/image_pull.go
  pkg/server/image_pull_test.go
Labels: size/M

#1330 missed the release version for HEAD in table-1
  README.md
Labels: lgtm, size/XS
