Repository containerd/cri, pull requests merged in 2019-01, with the labels that each got.

#1000 Teardown sandbox network after stop.
  pkg/server/sandbox_stop.go
Labels: lgtm, size/S

#1016 [release/1.0] Specify platform for image pull.
  pkg/server/image_pull.go
Labels: lgtm, size/XS

#1010 Fix the issue that pod or container config file without metadata will…
  pkg/server/container_create.go
  pkg/server/sandbox_run.go
Labels: lgtm, ok-to-test, size/S

#970 support DisableCgroup, DisableApparmor, RestrictOOMScoreAdj
  docs/config.md
  pkg/config/config.go
  pkg/server/container_create.go
  pkg/server/helpers.go
  pkg/server/sandbox_run.go
  pkg/server/service.go
Labels: lgtm, size/L

#1017 Add unit test for DisableCgroup, RestrictOOMScoreAdj.
  pkg/server/container_create_test.go
  pkg/server/helpers_test.go
  pkg/server/sandbox_run_test.go
Labels: lgtm, size/M

#1020 Add test for shared pid multi-process container stop.
  integration/container_stop_test.go
  integration/test_utils.go
Labels: lgtm, size/L

#1019 Add integration test for RunPodSandbox and CreateContainer
  integration/container_create_test.go
  integration/sandbox_run_test.go
Labels: lgtm, ok-to-test, size/M

#1027 Fix the log ending newline handling.
  integration/container_log_test.go
  pkg/server/events.go
  pkg/server/io/logger.go
  pkg/server/io/logger_test.go
  pkg/util/strings.go
Labels: lgtm, size/L

#1025 Fix some typos in comment
  pkg/server/streaming.go
  pkg/store/snapshot/snapshot.go
Labels: lgtm, ok-to-test, size/XS

#1032 Don't use string when there is a constant.
  integration/pod_hostname_env_test.go
Labels: lgtm, size/XS

#1030 Cherrypick #1027 release 1.2
  integration/container_log_test.go
  integration/image_load_test.go
  pkg/server/events.go
  pkg/server/io/logger.go
  pkg/server/io/logger_test.go
  pkg/util/strings.go
Labels: cherrypick, lgtm, size/L

#1029 Add a generic runtime options api.
  Makefile
  hack/update-proto.sh
  pkg/api/runtimeoptions/v1/api.pb.go
  pkg/api/runtimeoptions/v1/api.proto
  pkg/api/v1/api.pb.go
  pkg/api/v1/api.proto
  pkg/server/helpers.go
Labels: lgtm, size/L

#1031 Cherrypick #1027 release 1.0
  integration/container_log_test.go
  pkg/server/events.go
  pkg/server/io/logger.go
  pkg/server/io/logger_test.go
  pkg/util/strings.go
Labels: cherrypick, lgtm, size/L

#1028 hack/Makefile: detect dirty vendor
  Makefile
  hack/verify-vendor.sh
Labels: lgtm, size/M

#1034 hack: handle additional cleanup from #1028
  hack/verify-vendor.sh
Labels: lgtm, size/XS

#1035 Add RUNTIME env in integration and cri test.
  hack/test-cri.sh
  hack/test-integration.sh
Labels: lgtm, size/XS
