Repository containerd/cri, pull requests merged in 2019-12, with the labels that each got.

#1344 Provide resolvConf to sandbox container's mounts
  pkg/server/sandbox_run_unix.go
Labels: lgtm, ok-to-test, size/XS

#1348 update kubernetes dependency to v1.16.3
  vendor.conf
  vendor/github.com/json-iterator/go/iter.go
  vendor/github.com/json-iterator/go/iter_array.go
  vendor/github.com/json-iterator/go/iter_object.go
  vendor/github.com/json-iterator/go/iter_skip_sloppy.go
  vendor/github.com/json-iterator/go/reflect.go
  vendor/github.com/json-iterator/go/reflect_extension.go
  vendor/github.com/json-iterator/go/reflect_map.go
  vendor/github.com/json-iterator/go/reflect_marshaler.go
  vendor/github.com/json-iterator/go/reflect_struct_decoder.go
  vendor/github.com/modern-go/reflect2/type_map.go
  vendor/github.com/stretchr/testify/README.md
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/go.mod
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/golang.org/x/time/go.mod
  vendor/gopkg.in/inf.v0/dec.go
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/k8s.io/api/go.mod
  vendor/k8s.io/apimachinery/go.mod
  vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go
  vendor/k8s.io/apimachinery/pkg/util/intstr/intstr.go
  vendor/k8s.io/apimachinery/pkg/util/json/json.go
  vendor/k8s.io/apiserver/go.mod
  vendor/k8s.io/client-go/go.mod
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/kubernetes/go.mod
  vendor/k8s.io/utils/README.md
  vendor/k8s.io/utils/go.mod
Labels: lgtm, ok-to-test, size/XXL

#1346 [release/1.3] Add insecure_skip_verify option.
  docs/registry.md
  pkg/config/config.go
  pkg/server/image_pull.go
Labels: lgtm, size/M

#1349 Use containerD WithHostDevices
  pkg/containerd/opts/spec_unix.go
  pkg/server/container_create_unix.go
Labels: lgtm, size/M

#1351 Better handle unknown state.
  pkg/server/events.go
  pkg/server/helpers.go
  pkg/server/restart.go
  pkg/store/container/status.go
  pkg/store/container/status_test.go
Labels: cherrypick-needed, lgtm, size/S

#1354 [release/1.2] Better handle unknown state.
  pkg/server/events.go
  pkg/server/helpers.go
  pkg/server/restart.go
  pkg/store/container/status.go
  pkg/store/container/status_test.go
Labels: cherrypick, lgtm, size/S

#1353 [release/1.3] Better handle unknown state.
  pkg/server/events.go
  pkg/server/helpers.go
  pkg/server/restart.go
  pkg/store/container/status.go
  pkg/store/container/status_test.go
Labels: cherrypick, lgtm, size/S

#1358 add removal of old go
  .appveyor.yml
Labels: lgtm, priority/P0, size/XS

#1356 Fix privileged support
  .appveyor.yml
  .travis.yml
  pkg/server/container_create_unix.go
Labels: lgtm, priority/P0, size/S

#1357 integration: Add container restart test
  integration/container_restart_test.go
Labels: lgtm, ok-to-test, size/M

#1359 bump up the default runtime to "io.containerd.runc.v2"
  docs/config.md
  pkg/config/config_unix.go
  pkg/server/sandbox_run_unix.go
Labels: lgtm, size/S

#1360 [release/1.3] fix NoPivot for RuntimeRuncV2
  pkg/server/sandbox_run.go
Labels: lgtm, size/XS
