Repository containerd/cri, pull requests merged in 2019-11, with the labels that each got.

#1331 Fix using `http` for localhost, 127.0.0.1 and ::1 by default
  pkg/server/image_pull.go
Labels: lgtm, ok-to-test, size/XS

#1337 [WCOW] Clean mount path for windows
  pkg/containerd/opts/spec_windows.go
  pkg/server/container_create_windows_test.go
Labels: lgtm, size/S

#1338 [WCOW] Add windows release tar for test
  Makefile
  hack/install/utils.sh
  hack/install/windows/install-cni-config.sh
  hack/install/windows/install-cni.sh
  hack/install/windows/install-hcsshim.sh
  hack/release-windows.sh
  hack/release.sh
  test/windows/build.sh
  vendor.conf
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/http_util.go
  vendor/google.golang.org/grpc/version.go
Labels: lgtm, size/L

#1345 Add insecure_skip_verify option.
  docs/registry.md
  pkg/config/config.go
  pkg/server/image_pull.go
Labels: cherrypick-needed, lgtm, size/M

#1347 Fix typo.
  docs/registry.md
Labels: lgtm, size/XS
