Repository containerd/cri, pull requests merged in 2019-02, with the labels that each got.

#1038 Cherrypick #1037 release 1.2
  hack/test-integration.sh
  integration/restart_test.go
  pkg/server/container_remove.go
  pkg/server/container_status.go
  pkg/server/container_stop.go
  pkg/server/events.go
  pkg/server/helpers.go
  pkg/server/restart.go
  pkg/server/sandbox_list_test.go
  pkg/server/sandbox_remove.go
  pkg/server/sandbox_run.go
  pkg/server/sandbox_status.go
  pkg/server/sandbox_status_test.go
  pkg/server/sandbox_stop.go
  pkg/store/container/container.go
  pkg/store/container/status.go
  pkg/store/sandbox/sandbox.go
  pkg/store/sandbox/sandbox_test.go
  pkg/store/sandbox/status.go
  pkg/store/sandbox/status_test.go
  vendor.conf
  vendor/github.com/containerd/containerd/archive/tar.go
  vendor/github.com/containerd/containerd/archive/tar_windows.go
  vendor/github.com/containerd/containerd/client.go
  vendor/github.com/containerd/containerd/content/local/locks.go
  vendor/github.com/containerd/containerd/contrib/seccomp/seccomp.go
  vendor/github.com/containerd/containerd/diff/apply/apply.go
  vendor/github.com/containerd/containerd/filters/scanner.go
  vendor/github.com/containerd/containerd/import.go
  vendor/github.com/containerd/containerd/metadata/content.go
  vendor/github.com/containerd/containerd/metadata/db.go
  vendor/github.com/containerd/containerd/metadata/gc.go
  vendor/github.com/containerd/containerd/metadata/snapshot.go
  vendor/github.com/containerd/containerd/mount/mountinfo_linux.go
  vendor/github.com/containerd/containerd/pkg/progress/escape.go
  vendor/github.com/containerd/containerd/plugin/plugin.go
  vendor/github.com/containerd/containerd/process.go
  vendor/github.com/containerd/containerd/remotes/docker/auth.go
  vendor/github.com/containerd/containerd/remotes/docker/converter.go
  vendor/github.com/containerd/containerd/runtime/runtime.go
  vendor/github.com/containerd/containerd/runtime/v1/linux/proc/deleted_state.go
  vendor/github.com/containerd/containerd/runtime/v1/linux/proc/exec.go
  vendor/github.com/containerd/containerd/runtime/v1/linux/proc/exec_state.go
  vendor/github.com/containerd/containerd/runtime/v1/linux/proc/init.go
  vendor/github.com/containerd/containerd/runtime/v1/linux/proc/init_state.go
  vendor/github.com/containerd/containerd/runtime/v1/linux/proc/io.go
  vendor/github.com/containerd/containerd/runtime/v1/linux/proc/utils.go
  vendor/github.com/containerd/containerd/runtime/v1/linux/runtime.go
  vendor/github.com/containerd/containerd/runtime/v2/manager.go
  vendor/github.com/containerd/containerd/runtime/v2/shim/shim_unix.go
  vendor/github.com/containerd/containerd/runtime/v2/shim/shim_windows.go
  vendor/github.com/containerd/containerd/runtime/v2/shim/util_windows.go
  vendor/github.com/containerd/containerd/runtime/v2/shim_unix.go
  vendor/github.com/containerd/containerd/services/containers/local.go
  vendor/github.com/containerd/containerd/services/images/local.go
  vendor/github.com/containerd/containerd/task.go
  vendor/github.com/containerd/containerd/vendor.conf
  vendor/github.com/containerd/containerd/version/version.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/intelrdt.go
Labels: lgtm, size/XXL

#1040 Replace util.NormalizeImageRef with reference.ParseDockerRef
  pkg/containerd/importer/importer.go
  pkg/server/helpers.go
  pkg/server/helpers_test.go
  pkg/server/image_pull.go
  pkg/util/image.go
  vendor.conf
  vendor/github.com/docker/distribution/README.md
  vendor/github.com/docker/distribution/reference/normalize.go
  vendor/github.com/docker/distribution/reference/reference.go
  vendor/github.com/docker/distribution/vendor.conf
Labels: lgtm, ok-to-test, size/L

#1043 Update containerd to 4543e32a8b29e691e523ddc142f0c9068917df54
  vendor.conf
  vendor/github.com/containerd/containerd/cmd/ctr/commands/run/run_windows.go
  vendor/github.com/containerd/containerd/images/archive/reference.go
  vendor/github.com/containerd/containerd/metadata/buckets.go
  vendor/github.com/containerd/containerd/oci/spec.go
  vendor/github.com/containerd/containerd/oci/spec_opts_windows.go
  vendor/github.com/containerd/containerd/vendor.conf
Labels: lgtm, needs-ok-to-test, size/L

#1042 Set /etc/hostname.
  integration/pod_hostname_test.go
  pkg/server/container_create.go
  pkg/server/container_create_test.go
  pkg/server/helpers.go
  pkg/server/sandbox_run.go
  pkg/server/sandbox_run_test.go
Labels: lgtm, size/L

#1045 Fix env performance issue
  pkg/server/container_create.go
  pkg/server/container_create_test.go
  pkg/server/helpers.go
  pkg/server/helpers_test.go
  pkg/server/instrumented_service.go
  pkg/server/sandbox_run.go
Labels: lgtm, size/L

#1046 Cherrypick #1042 release 1.2
  integration/pod_hostname_test.go
  pkg/server/container_create.go
  pkg/server/container_create_test.go
  pkg/server/helpers.go
  pkg/server/sandbox_run.go
  pkg/server/sandbox_run_test.go
Labels: cherrypick, lgtm, size/L

#1047 Cherrypick #1042 release 1.0
  integration/pod_hostname_test.go
  integration/test_utils.go
  pkg/server/container_create.go
  pkg/server/container_create_test.go
  pkg/server/helpers.go
  pkg/server/sandbox_run.go
  pkg/server/sandbox_run_test.go
Labels: cherrypick, lgtm, size/L

#1049 Cherrypick #1045 release 1.2
  pkg/server/container_create.go
  pkg/server/container_create_test.go
  pkg/server/helpers.go
  pkg/server/helpers_test.go
  pkg/server/instrumented_service.go
  pkg/server/sandbox_run.go
Labels: lgtm, size/L

#1048 Cherrypick #1045 release 1.0
  pkg/server/container_create.go
  pkg/server/container_create_test.go
  pkg/server/helpers.go
  pkg/server/helpers_test.go
  pkg/server/instrumented_service.go
  pkg/server/sandbox_run.go
Labels: cherrypick, lgtm, size/L

#1053 update support statment reflecting eol for k8s 1.10
  README.md
  docs/kube-up.md
Labels: lgtm, size/S

#1065 Fix architecture doc
  docs/architecture.md
Labels: lgtm, ok-to-test, size/XS

#1066 Add more explanation about the CRI config.
  docs/config.md
Labels: kind/docs, lgtm, size/XS

#1063 Add RuntimeHandler into PodSandbox and PodSandboxStatus
  integration/runtime_handler_test.go
  pkg/server/sandbox_list.go
  pkg/server/sandbox_list_test.go
  pkg/server/sandbox_status.go
  pkg/server/sandbox_status_test.go
Labels: lgtm, ok-to-test, size/L

#1060 Support stream idle timeout.
  cri.go
  docs/config.md
  pkg/config/config.go
  pkg/server/service.go
  pkg/server/streaming.go
Labels: lgtm, size/M

#1055 Use the correct sandbox config.
  pkg/server/container_create.go
Labels: lgtm, size/XS
