Repository containerd/cri, pull requests merged in 2019-05, with the labels that each got.

#1140 Integration test task.Delete fix
  integration/sandbox_clean_remove_test.go
Labels: lgtm, ok-to-test, size/XS

#1142 Log failed registry mirror attempt in debug.
  pkg/server/image_pull.go
Labels: lgtm, size/XS

#1146 Forward sandbox config to PullImage request
  pkg/server/helpers.go
  pkg/server/sandbox_run.go
Labels: lgtm, size/XS

#1147 Move from unix to syscall package for SIG* signals
  pkg/server/container_execsync.go
  pkg/server/container_stop.go
  pkg/server/sandbox_stop.go
Labels: lgtm, size/S

#1145 Fix typo in WithoutRunMount
  pkg/containerd/opts/spec.go
Labels: lgtm, size/XS

#1148 Override container log path to empty if either of sandbox log directory or container log path is empty.
  pkg/server/container_create.go
Labels: lgtm, ok-to-test, size/XS

#1153 Update parseDNSOptions maxDNSSearches in error message
  pkg/server/sandbox_run.go
Labels: lgtm, size/XS

#1156 Make sure exec process is killed when context is canceled.
  pkg/server/container_execsync.go
Labels: lgtm, size/XS

#1151 Initial support for traffic shaping
  pkg/server/sandbox_run.go
  vendor.conf
  vendor/github.com/containerd/go-cni/namespace_opts.go
  vendor/github.com/containerd/go-cni/opts.go
  vendor/github.com/containerd/go-cni/types.go
  vendor/k8s.io/kubernetes/pkg/util/bandwidth/doc.go
  vendor/k8s.io/kubernetes/pkg/util/bandwidth/fake_shaper.go
  vendor/k8s.io/kubernetes/pkg/util/bandwidth/interfaces.go
  vendor/k8s.io/kubernetes/pkg/util/bandwidth/linux.go
  vendor/k8s.io/kubernetes/pkg/util/bandwidth/unsupported.go
  vendor/k8s.io/kubernetes/pkg/util/bandwidth/utils.go
Labels: lgtm, ok-to-test, size/XL

#1157 Minor typo in toCNIBandWidth
  pkg/server/sandbox_run.go
Labels: lgtm, size/XS
