Repository containerd/cri, pull requests merged in 2019-04, with the labels that each got.

#1102 Uts namespace and fix array
  integration/pod_hostname_test.go
  pkg/containerd/opts/spec.go
  pkg/containerd/opts/spec_test.go
  pkg/server/sandbox_run.go
  pkg/server/sandbox_run_test.go
Labels: cherrypick, lgtm, size/M

#1109 Cherrypick #1108 release 1.2
  vendor.conf
Labels: lgtm, size/XS

#1110 Cherrypick #1108 release 1.0
  vendor.conf
Labels: lgtm, size/XS

#1111 Cherrypick #1102 release 1.2
  integration/pod_hostname_test.go
  pkg/server/sandbox_run.go
  pkg/server/sandbox_run_test.go
Labels: lgtm, size/M

#1112 Cherrypick #1102 release 1.0
  integration/pod_hostname_test.go
  pkg/server/sandbox_run.go
  pkg/server/sandbox_run_test.go
Labels: lgtm, size/M

#1114 Use local env to avoid writing to passed-in readonly env.
  cluster/gce/configure.sh
Labels: lgtm, size/S

#1113 bump opencontainers/selinux v1.2.1
  vendor.conf
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
Labels: lgtm, ok-to-test, size/XS

#1116 Enable runc.v2 as the default runtime in test.
  cluster/gce/configure.sh
  pkg/server/helpers.go
  pkg/server/helpers_test.go
Labels: lgtm, size/M

#1115 [release/1.2 backport] bump selinux v1.2.1
  pkg/server/helpers.go
  vendor.conf
  vendor/github.com/opencontainers/selinux/README.md
  vendor/github.com/opencontainers/selinux/go-selinux/label/label.go
  vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
Labels: lgtm, ok-to-test, size/L

#1117 [release/1.0 backport] bump selinux v1.2.1
  pkg/server/helpers.go
  vendor.conf
  vendor/github.com/opencontainers/selinux/README.md
  vendor/github.com/opencontainers/selinux/go-selinux/label/label.go
  vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
Labels: lgtm, ok-to-test, size/L

#1118 Support comment in vendor.
  hack/utils.sh
Labels: lgtm, size/XS

#1119 Cherrypick #1118 release 1.0
  hack/utils.sh
Labels: lgtm, size/XS

#1120 Cherrypick #1118 release 1.2
  hack/utils.sh
Labels: lgtm, size/XS

#1122 [release 1.0] Update containerd to v1.1.7.
  vendor.conf
  vendor/github.com/containerd/cgroups/cgroup.go
  vendor/github.com/containerd/cgroups/control.go
  vendor/github.com/containerd/cgroups/cpuset.go
  vendor/github.com/containerd/cgroups/metrics.pb.go
  vendor/github.com/containerd/cgroups/metrics.proto
  vendor/github.com/containerd/cgroups/rdma.go
  vendor/github.com/containerd/cgroups/subsystem.go
  vendor/github.com/containerd/cgroups/utils.go
  vendor/github.com/containerd/containerd/archive/tar.go
  vendor/github.com/containerd/containerd/contrib/seccomp/seccomp_default.go
  vendor/github.com/containerd/containerd/image.go
  vendor/github.com/containerd/containerd/linux/proc/io.go
  vendor/github.com/containerd/containerd/vendor.conf
  vendor/github.com/containerd/containerd/version/version.go
  vendor/github.com/containerd/go-runc/console.go
  vendor/github.com/containerd/go-runc/runc.go
  vendor/github.com/containerd/go-runc/utils.go
  vendor/github.com/opencontainers/runc/README.md
  vendor/github.com/opencontainers/runc/libcontainer/nsenter/cloned_binary.c
  vendor/github.com/opencontainers/runc/vendor.conf
  vendor/github.com/opencontainers/runtime-spec/README.md
  vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
Labels: lgtm, size/XXL

#1123 [release 1.2] Update containerd to v1.2.6.
  vendor.conf
  vendor/github.com/containerd/cgroups/cgroup.go
  vendor/github.com/containerd/containerd/contrib/seccomp/seccomp_default.go
  vendor/github.com/containerd/containerd/mount/mountinfo_linux.go
  vendor/github.com/containerd/containerd/oci/spec_opts.go
  vendor/github.com/containerd/containerd/runtime/v1/linux/proc/io.go
  vendor/github.com/containerd/containerd/vendor.conf
  vendor/github.com/opencontainers/runc/libcontainer/nsenter/cloned_binary.c
  vendor/github.com/opencontainers/runc/vendor.conf
Labels: lgtm, size/M

#1124 Use golang 1.11.6 for now.
  .travis.yml
Labels: lgtm, size/XS

#1130 Update go-cni to 891c2a41e18144b2d7921f971d6c9789a68046b2.
  pkg/server/testing/fake_cni_plugin.go
  vendor.conf
  vendor/github.com/containerd/go-cni/README.md
  vendor/github.com/containerd/go-cni/cni.go
  vendor/github.com/containerd/go-cni/errors.go
  vendor/github.com/containerd/go-cni/opts.go
  vendor/github.com/containerd/go-cni/result.go
Labels: lgtm, size/L

#1129 Use runc.v1 for now for debugging.
  cluster/gce/configure.sh
Labels: lgtm, size/XS

#1134 Use ctr images import.
  cluster/gce/env
  docs/crictl.md
Labels: lgtm, size/XS

#1125 Add default runtime name
  cluster/gce/configure.sh
  cri.go
  docs/config.md
  pkg/config/config.go
  pkg/server/helpers_test.go
  pkg/server/sandbox_run.go
  pkg/server/sandbox_run_test.go
Labels: lgtm, size/L

#1137 Use per-pod shim.
  cluster/gce/configure.sh
  vendor/github.com/gogo/googleapis/go.mod
  vendor/github.com/gogo/protobuf/go.mod
  vendor/github.com/sirupsen/logrus/go.mod
  vendor/golang.org/x/sys/go.mod
  vendor/gopkg.in/yaml.v2/go.mod
Labels: lgtm, size/S
