Repository containerd/cri, pull requests merged in 2019-06, with the labels that each got.

#1144 Add TLS auth registry support
  docs/registry.md
  pkg/config/config.go
  pkg/server/image_pull.go
Labels: lgtm, ok-to-test, size/M

#1158 adds cni config data to the cri status/info
  pkg/server/status.go
  pkg/store/sandbox/metadata.go
Labels: lgtm, size/XS

#1159 Cherrypick #1156 release 1.2
  pkg/server/container_execsync.go
Labels: lgtm, size/XS

#1160 Remove an unused TODO.
  pkg/store/container/status.go
Labels: lgtm, size/XS

#1155 add cni plugin config file max num config
  docs/config.md
  pkg/config/config.go
  pkg/server/service.go
  vendor.conf
  vendor/github.com/containerd/go-cni/cni.go
  vendor/github.com/containerd/go-cni/opts.go
  vendor/github.com/containerd/go-cni/types.go
Labels: lgtm, ok-to-test, size/M

#1165 fix: fix CRI dead link
  README.md
Labels: lgtm, ok-to-test, size/XS

#1162 Add cri managed image label when pulling the image.
  pkg/server/image_pull.go
Labels: cherrypick, lgtm, size/XS

#1166 doc update for cni max num
  docs/config.md
  pkg/config/config.go
Labels: lgtm, size/S

#1167 Cherrypick #1162 release 1.2
  pkg/server/image_pull.go
Labels: lgtm, size/XS

#1171 Fix http proxy ENV when TLS is enabled.
  pkg/server/image_pull.go
Labels: lgtm, size/M

#1178 use dynamic slack link
  README.md
Labels: lgtm, size/XS

#1180 Fix runc and critools version in release.
  hack/install/install-critools.sh
  hack/install/install-runc.sh
Labels: cherrypick, lgtm, size/XS

#1186 Revert "[release/1.2] Update containerd to v1.2.7"
  vendor.conf
  vendor/github.com/containerd/containerd/api/types/descriptor.pb.go
  vendor/github.com/containerd/containerd/api/types/descriptor.proto
  vendor/github.com/containerd/containerd/content/local/writer.go
  vendor/github.com/containerd/containerd/diff.go
  vendor/github.com/containerd/containerd/diff/walking/differ.go
  vendor/github.com/containerd/containerd/image_store.go
  vendor/github.com/containerd/containerd/metadata/adaptors.go
  vendor/github.com/containerd/containerd/metadata/boltutil/helpers.go
  vendor/github.com/containerd/containerd/metadata/images.go
  vendor/github.com/containerd/containerd/remotes/docker/authorizer.go
  vendor/github.com/containerd/containerd/remotes/docker/resolver.go
  vendor/github.com/containerd/containerd/remotes/resolver.go
  vendor/github.com/containerd/containerd/runtime/v1/linux/proc/deleted_state.go
  vendor/github.com/containerd/containerd/runtime/v1/linux/runtime.go
  vendor/github.com/containerd/containerd/runtime/v1/linux/task.go
  vendor/github.com/containerd/containerd/runtime/v1/shim.go
  vendor/github.com/containerd/containerd/runtime/v1/shim/client/client.go
  vendor/github.com/containerd/containerd/runtime/v1/shim/service.go
  vendor/github.com/containerd/containerd/runtime/v2/binary.go
  vendor/github.com/containerd/containerd/runtime/v2/shim.go
  vendor/github.com/containerd/containerd/runtime/v2/shim_unix.go
  vendor/github.com/containerd/containerd/services/diff/local.go
  vendor/github.com/containerd/containerd/services/images/helpers.go
  vendor/github.com/containerd/containerd/services/server/server_solaris.go
  vendor/github.com/containerd/containerd/services/tasks/local.go
  vendor/github.com/containerd/containerd/task.go
  vendor/github.com/containerd/containerd/task_opts.go
  vendor/github.com/containerd/containerd/vendor.conf
  vendor/github.com/containerd/containerd/version/version.go
  vendor/github.com/containerd/ttrpc/README.md
  vendor/github.com/containerd/ttrpc/client.go
  vendor/github.com/containerd/ttrpc/server.go
  vendor/github.com/containerd/ttrpc/services.go
  vendor/github.com/containerd/ttrpc/types.go
  vendor/github.com/opencontainers/runc/vendor.conf
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
Labels: size/XL

#1189 bump libseccomp-golang v0.9.1
  vendor.conf
  vendor/github.com/seccomp/libseccomp-golang/README
  vendor/github.com/seccomp/libseccomp-golang/seccomp.go
  vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go
Labels: cherrypick, lgtm, ok-to-test, size/L
