Repository containerd/cri, pull requests merged in 2019-03, with the labels that each got.

#1067 Cherrypick #1055 release 1.2
  pkg/server/container_create.go
Labels: lgtm, size/XS

#1068 Cherrypick #1055 release 1.0
  pkg/server/container_create.go
Labels: lgtm, size/XS

#1072 Use clean path for map and comparison.
  pkg/server/container_create.go
  pkg/server/container_create_test.go
  pkg/server/helpers.go
Labels: lgtm, size/S

#1073 Cherrypick #1072 release 1.0
  pkg/server/container_create.go
  pkg/server/container_create_test.go
  pkg/server/helpers.go
Labels: cherrypick, lgtm, size/S

#1074 Cherrypick #1072 release 1.2
  pkg/server/container_create.go
  pkg/server/container_create_test.go
  pkg/server/helpers.go
Labels: cherrypick, lgtm, size/S

#1056 Add an OCI annotation for sandbox log directory.
  pkg/annotations/annotations.go
  pkg/server/sandbox_run.go
  pkg/server/sandbox_run_test.go
Labels: lgtm, size/S

#1081 Cherrypick #1056 release 1.2
  pkg/annotations/annotations.go
  pkg/server/sandbox_run.go
  pkg/server/sandbox_run_test.go
Labels: lgtm, size/S

#1080 Use ParseSignal and AtomicWriteFile functions from containerd
  pkg/server/container_stop.go
  pkg/store/container/status.go
  vendor/github.com/docker/docker/pkg/ioutils/buffer.go
  vendor/github.com/docker/docker/pkg/ioutils/bytespipe.go
  vendor/github.com/docker/docker/pkg/ioutils/fswriters.go
  vendor/github.com/docker/docker/pkg/ioutils/readers.go
  vendor/github.com/docker/docker/pkg/ioutils/temp_unix.go
  vendor/github.com/docker/docker/pkg/ioutils/temp_windows.go
  vendor/github.com/docker/docker/pkg/ioutils/writeflusher.go
  vendor/github.com/docker/docker/pkg/ioutils/writers.go
  vendor/github.com/docker/docker/pkg/signal/README.md
  vendor/github.com/docker/docker/pkg/signal/signal.go
  vendor/github.com/docker/docker/pkg/signal/signal_darwin.go
  vendor/github.com/docker/docker/pkg/signal/signal_freebsd.go
  vendor/github.com/docker/docker/pkg/signal/signal_linux.go
  vendor/github.com/docker/docker/pkg/signal/signal_solaris.go
  vendor/github.com/docker/docker/pkg/signal/signal_unix.go
  vendor/github.com/docker/docker/pkg/signal/signal_unsupported.go
  vendor/github.com/docker/docker/pkg/signal/signal_windows.go
  vendor/github.com/docker/docker/pkg/signal/trap.go
Labels: lgtm, ok-to-test, size/XXL

#1083 Support docker 18.09 in the test script.
  cluster/gce/cloud-init/master.yaml
  cluster/gce/cloud-init/node.yaml
  test/e2e_node/init.yaml
Labels: lgtm, size/S

#1085 Fix /etc/hostname backward compatibility issue for in-place upgrade.
  pkg/server/container_create.go
  pkg/server/container_create_test.go
Labels: lgtm, size/M

#1086 Cherrypick #1085 release 1.2
  pkg/server/container_create.go
  pkg/server/container_create_test.go
Labels: cherrypick, lgtm, size/M

#1087 Cherrypick #1085 release 1.0
  pkg/server/container_create.go
  pkg/server/container_create_test.go
Labels: cherrypick, lgtm, size/M

#1088 clarify the versioning for the tarball
  docs/installation.md
Labels: kind/docs, lgtm, size/XS

#1069 Expose environment variables for configuring an additional runtime handler
  cluster/gce/configure.sh
Labels: lgtm, ok-to-test, size/S

#1092 Set default "" to extra runtime handler.
  cluster/gce/configure.sh
Labels: lgtm, size/XS

#1090 Add test for filtering container create masks when privileged
  pkg/server/container_create.go
  pkg/server/container_create_test.go
Labels: lgtm, size/M

#1084 Add support for passing sandbox annotations to runtime
  docs/config.md
  pkg/config/config.go
  pkg/server/container_create.go
  pkg/server/container_create_test.go
  pkg/server/helpers.go
  pkg/server/helpers_test.go
  pkg/server/sandbox_run.go
  pkg/server/sandbox_run_test.go
Labels: lgtm, ok-to-test, size/L

#1097 Support docker 18.09 in the test script.
  cluster/gce/cloud-init/master.yaml
  cluster/gce/cloud-init/node.yaml
  test/e2e_node/init.yaml
Labels: lgtm, size/S

#1096 Cleanup pod annotation test and only support wildcard
  docs/config.md
  pkg/config/config.go
  pkg/server/container_create.go
  pkg/server/container_create_test.go
  pkg/server/helpers.go
  pkg/server/helpers_test.go
  pkg/server/sandbox_run_test.go
Labels: lgtm, size/L

#1099 Do not SIGKILL container if container stop is cancelled.
  integration/container_stop_test.go
  pkg/server/container_stop.go
  pkg/server/sandbox_stop.go
Labels: lgtm, size/M

#1106 Update containerd to f2a20ead833f8caf3ffc12be058d6ce668b4ebed.
  vendor.conf
  vendor/github.com/Microsoft/go-winio/pkg/etw/etw.go
  vendor/github.com/Microsoft/go-winio/pkg/etw/eventdata.go
  vendor/github.com/Microsoft/go-winio/pkg/etw/eventdatadescriptor.go
  vendor/github.com/Microsoft/go-winio/pkg/etw/eventdescriptor.go
  vendor/github.com/Microsoft/go-winio/pkg/etw/eventmetadata.go
  vendor/github.com/Microsoft/go-winio/pkg/etw/eventopt.go
  vendor/github.com/Microsoft/go-winio/pkg/etw/fieldopt.go
  vendor/github.com/Microsoft/go-winio/pkg/etw/provider.go
  vendor/github.com/Microsoft/go-winio/pkg/etw/providerglobal.go
  vendor/github.com/Microsoft/go-winio/pkg/etw/ptr64_32.go
  vendor/github.com/Microsoft/go-winio/pkg/etw/ptr64_64.go
  vendor/github.com/Microsoft/go-winio/pkg/etw/zsyscall_windows.go
  vendor/github.com/Microsoft/go-winio/pkg/etwlogrus/hook.go
  vendor/github.com/Microsoft/hcsshim/internal/hcs/log.go
  vendor/github.com/Microsoft/hcsshim/internal/hcs/process.go
  vendor/github.com/Microsoft/hcsshim/internal/hcs/system.go
  vendor/github.com/Microsoft/hcsshim/internal/hcs/waithelper.go
  vendor/github.com/Microsoft/hcsshim/internal/hns/hnsnetwork.go
  vendor/github.com/Microsoft/hcsshim/internal/logfields/fields.go
  vendor/github.com/Microsoft/hcsshim/internal/safefile/safeopen.go
  vendor/github.com/Microsoft/hcsshim/internal/schema2/plan9_share.go
  vendor/github.com/Microsoft/hcsshim/vendor.conf
  vendor/github.com/containerd/containerd/api/types/descriptor.pb.go
  vendor/github.com/containerd/containerd/api/types/descriptor.proto
  vendor/github.com/containerd/containerd/cmd/ctr/commands/images/images.go
  vendor/github.com/containerd/containerd/cmd/ctr/commands/images/import.go
  vendor/github.com/containerd/containerd/container_checkpoint_opts.go
  vendor/github.com/containerd/containerd/contrib/seccomp/seccomp_default.go
  vendor/github.com/containerd/containerd/defaults/defaults_windows.go
  vendor/github.com/containerd/containerd/diff.go
  vendor/github.com/containerd/containerd/image_store.go
  vendor/github.com/containerd/containerd/import.go
  vendor/github.com/containerd/containerd/metadata/adaptors.go
  vendor/github.com/containerd/containerd/metadata/boltutil/helpers.go
  vendor/github.com/containerd/containerd/metadata/images.go
  vendor/github.com/containerd/containerd/oci/spec_opts.go
  vendor/github.com/containerd/containerd/services/content/contentserver/contentserver.go
  vendor/github.com/containerd/containerd/services/content/service.go
  vendor/github.com/containerd/containerd/services/diff/local.go
  vendor/github.com/containerd/containerd/services/images/helpers.go
  vendor/github.com/containerd/containerd/services/server/server.go
  vendor/github.com/containerd/containerd/services/tasks/local.go
  vendor/github.com/containerd/containerd/sys/filesys_unix.go
  vendor/github.com/containerd/containerd/sys/filesys_windows.go
  vendor/github.com/containerd/containerd/task.go
  vendor/github.com/containerd/containerd/task_opts.go
  vendor/github.com/containerd/containerd/vendor.conf
Labels: lgtm, size/XXL

#1104 Cherrypick #1099 release 1.2
  integration/container_stop_test.go
  pkg/server/container_stop.go
  pkg/server/sandbox_stop.go
Labels: lgtm, size/L

#1105 Cherrypick #1099 release 1.0
  integration/container_stop_test.go
  integration/test_utils.go
  pkg/server/container_stop.go
  pkg/server/sandbox_stop.go
Labels: lgtm, size/L

#1101 bump opencontainers/selinux to v1.2
  pkg/server/helpers.go
  vendor.conf
  vendor/github.com/opencontainers/selinux/README.md
  vendor/github.com/opencontainers/selinux/go-selinux/label/label.go
  vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
Labels: lgtm, ok-to-test, size/L

#1108 Update CNI to v0.7.5.
  vendor.conf
Labels: cherrypick, lgtm, size/XS
