Repository containerd/cri, pull requests merged in 2019-09, with the labels that each got.

#1252 Update cri-tools to fix all image reference test failure.
  hack/utils.sh
Labels: size/XS

#1259 Fix panic for task in unknown state.
  pkg/server/io/container_io.go
  pkg/server/io/helpers.go
Labels: cherrypick-needed, lgtm, size/M

#1256 Clarify exec behavior in some edge cases
  pkg/server/container_execsync.go
Labels: size/S

#1266 Support local containerd release.
  hack/release.sh
Labels: cherrypick-needed, lgtm, size/S

#1265 [release/1.3] Fix panic for task in unknown state.
  pkg/server/io/container_io.go
  pkg/server/io/helpers.go
Labels: cherrypick, lgtm, size/M

#1267 [release/1.3] Support local containerd release.
  hack/release.sh
Labels: cherrypick, lgtm, size/S

#1271 need to move instr to more recent golang; remove integration/*.go from lint verify test
  Makefile
  README.md
Labels: lgtm, size/XS

#1281 Move golangci-lint configuration out of Makefile
  .golangci.yml
  Makefile
  pkg/containerd/opts/spec_unix.go
  pkg/containerd/opts/spec_windows.go
  pkg/netns/netns_windows.go
Labels: lgtm, size/M

#1280 Add back default UNIX env to container config
  pkg/server/container_create_unix.go
  pkg/server/container_create_unix_test.go
Labels: cherrypick-needed, kind/bug, lgtm, size/S

#1283 [release/1.2] Backport fix for default UNIX environment in OCI container config
  pkg/server/container_create.go
  pkg/server/container_create_test.go
Labels: cherrypick, lgtm, size/S

#1289 Ignore temporary permission denied error.
  test/windows/runner.sh
Labels: lgtm, size/M

#1291 Fix indent in cni.template.
  cluster/gce/cni.template
Labels: size/XS

#1284 Add windows port forward support
  hack/utils.sh
  pkg/config/config_windows.go
  pkg/server/container_execsync.go
  pkg/server/sandbox_portforward.go
  pkg/server/sandbox_portforward_unix.go
  pkg/server/sandbox_portforward_windows.go
  pkg/server/streaming.go
  test/windows/test.sh
Labels: lgtm, size/L

#1294 Forward SandboxConfig.Hostname to Workload container activation
  pkg/server/container_create_windows.go
Labels: lgtm, size/XS

#1292 Document simpler kube-up.sh
  docs/kube-up.md
Labels: kind/docs, lgtm, size/XS

#1287 Use type alias from containerd for cgroup metric types
  pkg/server/container_stats_list_unix.go
  vendor.conf
  vendor/github.com/containerd/containerd/cmd/containerd/command/main.go
  vendor/github.com/containerd/containerd/diff/stream.go
  vendor/github.com/containerd/containerd/images/image.go
  vendor/github.com/containerd/containerd/images/mediatypes.go
  vendor/github.com/containerd/containerd/metrics/cgroups/blkio.go
  vendor/github.com/containerd/containerd/metrics/cgroups/cpu.go
  vendor/github.com/containerd/containerd/metrics/cgroups/hugetlb.go
  vendor/github.com/containerd/containerd/metrics/cgroups/memory.go
  vendor/github.com/containerd/containerd/metrics/cgroups/metric.go
  vendor/github.com/containerd/containerd/metrics/cgroups/metrics.go
  vendor/github.com/containerd/containerd/metrics/cgroups/pids.go
  vendor/github.com/containerd/containerd/metrics/types/v1/types.go
  vendor/github.com/containerd/containerd/oci/spec_opts.go
  vendor/github.com/containerd/containerd/platforms/database.go
  vendor/github.com/containerd/containerd/remotes/docker/scope.go
  vendor/github.com/containerd/containerd/remotes/handlers.go
  vendor/github.com/containerd/containerd/runtime/v2/binary.go
  vendor/github.com/containerd/containerd/runtime/v2/shim.go
  vendor/github.com/containerd/containerd/runtime/v2/shim/util_unix.go
  vendor/github.com/containerd/containerd/runtime/v2/shim/util_windows.go
  vendor/github.com/containerd/containerd/runtime/v2/shim_unix.go
  vendor/github.com/containerd/containerd/runtime/v2/shim_windows.go
  vendor/github.com/containerd/containerd/unpacker.go
  vendor/github.com/containerd/containerd/vendor.conf
Labels: lgtm, size/XL

#1296 Set keepalive for ssh in windows test.
  test/windows/runner.sh
Labels: size/S

#1298 Set default sandbox container cpu shares on windows.
  pkg/containerd/opts/spec.go
  pkg/containerd/opts/spec_unix.go
  pkg/containerd/opts/spec_windows.go
  pkg/server/sandbox_run_windows.go
  pkg/server/sandbox_run_windows_test.go
Labels: lgtm, size/M

#1300 Add hostname CRI validation and unit test.
  hack/utils.sh
  pkg/server/container_create_windows_test.go
Labels: lgtm, size/XS

#1301 [release/1.0] Make sure exec process is killed when context is canceled.
  pkg/server/container_execsync.go
Labels: lgtm, size/XS

#1303 [release/1.0] Sync vendors with containerd before release.
  vendor.conf
  vendor/github.com/opencontainers/runc/libcontainer/README.md
  vendor/github.com/opencontainers/runc/libcontainer/configs/blkio_device.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_unsupported.go
  vendor/github.com/opencontainers/runc/libcontainer/devices/devices.go
  vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsenter_unsupported.go
  vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c
  vendor/github.com/opencontainers/runc/libcontainer/system/syscall_linux_64.go
  vendor/github.com/opencontainers/runc/vendor.conf
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
  vendor/github.com/seccomp/libseccomp-golang/README
  vendor/github.com/seccomp/libseccomp-golang/seccomp.go
  vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go
Labels: lgtm, size/XL

#1302 [release/1.3] Update cri-tools to v1.16.1.
  hack/test-cri.sh
  hack/utils.sh
Labels: lgtm, size/XS

#1304 [release/1.2] Support local containerd release.
  hack/release.sh
Labels: cherrypick, lgtm, size/S

#1306 [WCOW] Extend permission denied retry to 3min.
  test/windows/runner.sh
Labels: lgtm, size/XS
