Repository containerd/cri, pull requests merged in 2020-09, with the labels that each got.

#1558 [1.3] remove libseccomp cgo dependency
  pkg/seccomp/fixtures/proc_self_status
  pkg/seccomp/seccomp_linux.go
  pkg/seccomp/seccomp_linux_test.go
  pkg/seccomp/seccomp_unsupported.go
  pkg/server/image_pull.go
  pkg/server/service.go
  vendor.conf
  vendor/github.com/opencontainers/runc/libcontainer/seccomp/config.go
  vendor/github.com/opencontainers/runc/libcontainer/seccomp/seccomp_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/seccomp/seccomp_unsupported.go
  vendor/github.com/seccomp/libseccomp-golang/LICENSE
  vendor/github.com/seccomp/libseccomp-golang/README
  vendor/github.com/seccomp/libseccomp-golang/seccomp.go
  vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go
Labels: size/XXL

#1561 Handle KVM based runtimes with selinux
  pkg/server/container_create.go
  pkg/server/helpers_unix.go
  pkg/server/helpers_windows.go
  pkg/server/sandbox_run.go
  pkg/seutil/seutil.go
Labels: size/L

#1571 README: Update slack reference to CNCF
  README.md
Labels: ok-to-test, size/XS

#1573 update cni config version
  hack/install/install-cni-config.sh
Labels: cherrypicked, size/XS

#1574 [release/1.4] update cni config version #1573
  hack/install/install-cni-config.sh
Labels: cherrypick, size/XS

#1577 Make script work for both python2.7 and 3.6
  cluster/gce/configure.sh
Labels: lgtm, ok-to-test, size/S

#1572 Limit size of additional annotation for avoiding unpack failure
  pkg/server/image_pull.go
  pkg/server/image_pull_test.go
Labels: ok-to-test, size/M

#1578 vendor: github.com/willf/bitset v1.1.11
  vendor.conf
  vendor/github.com/willf/bitset/README.md
  vendor/github.com/willf/bitset/bitset.go
  vendor/github.com/willf/bitset/go.mod
Labels: size/M

#1579 [release/1.4 backport] vendor: github.com/willf/bitset v1.1.11
  vendor.conf
  vendor/github.com/willf/bitset/README.md
  vendor/github.com/willf/bitset/bitset.go
  vendor/github.com/willf/bitset/go.mod
Labels: cherrypick, size/M

#1581 [release/1.4 backport] Make script work for both python2.7 and 3.6
  cluster/gce/configure.sh
Labels: size/S

#1584 Revert "Fix doc for runtime specific options"
  docs/config.md
Labels: size/M

#1570 Set masked and readonly paths based on default Unix spec
  pkg/server/container_create_unix.go
  pkg/server/container_create_unix_test.go
Labels: ok-to-test, size/S

#1562 Update to latest k8s 1.19.2 release
  vendor.conf
  vendor/k8s.io/api/go.mod
  vendor/k8s.io/apimachinery/go.mod
  vendor/k8s.io/apimachinery/pkg/runtime/converter.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/apimachinery/pkg/util/net/util.go
  vendor/k8s.io/apiserver/go.mod
  vendor/k8s.io/client-go/go.mod
  vendor/k8s.io/component-base/go.mod
  vendor/sigs.k8s.io/structured-merge-diff/v4/LICENSE
  vendor/sigs.k8s.io/structured-merge-diff/v4/README.md
  vendor/sigs.k8s.io/structured-merge-diff/v4/go.mod
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/allocator.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/doc.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/fields.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/jsontagutil.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/list.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/listreflect.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/listunstructured.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/map.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/mapreflect.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/mapunstructured.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/reflectcache.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/scalar.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/structreflect.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/value.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/valuereflect.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/valueunstructured.go
Labels: size/L

#1372 update config syntax in registry.md
  docs/registry.md
Labels: ok-to-test, size/M

#1587 vendor: containerd/containerd v1.4.1
  vendor.conf
  vendor/github.com/containerd/containerd/contrib/seccomp/seccomp_default.go
  vendor/github.com/containerd/containerd/runtime/v1/shim/client/client.go
  vendor/github.com/containerd/containerd/runtime/v1/shim/service.go
  vendor/github.com/containerd/containerd/runtime/v2/bundle.go
  vendor/github.com/containerd/containerd/services/tasks/local.go
  vendor/github.com/containerd/containerd/vendor.conf
  vendor/github.com/containerd/containerd/version/version.go
Labels: cherrypick-needed, size/L

#1586 [release/1.4 backport] Update to latest kubernetes v1.19.2
  vendor.conf
  vendor/k8s.io/api/go.mod
  vendor/k8s.io/apimachinery/go.mod
  vendor/k8s.io/apimachinery/pkg/runtime/converter.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/apimachinery/pkg/util/net/util.go
  vendor/k8s.io/apiserver/go.mod
  vendor/k8s.io/client-go/go.mod
  vendor/k8s.io/component-base/go.mod
  vendor/sigs.k8s.io/structured-merge-diff/v4/LICENSE
  vendor/sigs.k8s.io/structured-merge-diff/v4/README.md
  vendor/sigs.k8s.io/structured-merge-diff/v4/go.mod
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/allocator.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/doc.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/fields.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/jsontagutil.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/list.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/listreflect.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/listunstructured.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/map.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/mapreflect.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/mapunstructured.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/reflectcache.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/scalar.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/structreflect.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/value.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/valuereflect.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/valueunstructured.go
Labels: cherrypick, size/L

#1588 [release/1.4 backport] Set masked and readonly paths based on default Unix spec
  pkg/server/container_create_unix.go
  pkg/server/container_create_unix_test.go
Labels: cherrypick, size/S

#1589 [release/1.4 backport] vendor: containerd/containerd v1.4.1
  vendor.conf
  vendor/github.com/containerd/containerd/contrib/seccomp/seccomp_default.go
  vendor/github.com/containerd/containerd/runtime/v1/shim/client/client.go
  vendor/github.com/containerd/containerd/runtime/v1/shim/service.go
  vendor/github.com/containerd/containerd/runtime/v2/bundle.go
  vendor/github.com/containerd/containerd/services/tasks/local.go
  vendor/github.com/containerd/containerd/vendor.conf
  vendor/github.com/containerd/containerd/version/version.go
Labels: cherrypick, size/L

#1583 pkg/server: make ensureRemoveAll() an alias for os.RemoveAll() on Windows
  pkg/server/helpers_windows.go
Labels: size/M
