Repository containerd/cri, pull requests merged in 2020-04, with the labels that each got.

#1424 Start docker unconditionally
  test/e2e_node/init.yaml
Labels: lgtm, ok-to-test, size/XS

#1441 Running critest under windows using github action
  .github/workflows/ci.yml
  hack/install/install-containerd.sh
  test/windows/test.sh
Labels: ok-to-test, size/M

#1442 Create greetings.yml
  .github/workflows/greetings.yml
Labels: size/S

#1439 fixes bad unit test when selinux is enabled
  pkg/server/helpers_selinux_test.go
Labels: size/S

#1405 reload cni network config if has fs change events
  pkg/server/cni_conf_syncer.go
  pkg/server/service.go
  pkg/server/service_unix.go
  pkg/server/service_windows.go
  pkg/server/status.go
  vendor.conf
  vendor/github.com/fsnotify/fsnotify/LICENSE
  vendor/github.com/fsnotify/fsnotify/README.md
  vendor/github.com/fsnotify/fsnotify/fen.go
  vendor/github.com/fsnotify/fsnotify/fsnotify.go
  vendor/github.com/fsnotify/fsnotify/go.mod
  vendor/github.com/fsnotify/fsnotify/inotify.go
  vendor/github.com/fsnotify/fsnotify/inotify_poller.go
  vendor/github.com/fsnotify/fsnotify/kqueue.go
  vendor/github.com/fsnotify/fsnotify/open_mode_bsd.go
  vendor/github.com/fsnotify/fsnotify/open_mode_darwin.go
  vendor/github.com/fsnotify/fsnotify/windows.go
Labels: size/XXL

#1443 Build runc with selinux support
  Makefile
  README.md
  hack/install/utils.sh
  vendor.conf
  vendor/github.com/opencontainers/selinux/go-selinux/label/label.go
  vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
  vendor/github.com/opencontainers/selinux/go-selinux/label/label_stub.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
  vendor/github.com/opencontainers/selinux/go-selinux/xattrs.go
  vendor/github.com/opencontainers/selinux/pkg/pwalk/README.md
  vendor/github.com/opencontainers/selinux/pkg/pwalk/pwalk.go
Labels: ok-to-test, size/XL

#1438 Replace docker/distribution/reference with containerd/reference/docker
  pkg/server/helpers.go
  pkg/server/helpers_test.go
  pkg/server/image_pull.go
  pkg/util/image.go
  vendor/github.com/docker/distribution/reference/helpers.go
  vendor/github.com/docker/distribution/reference/normalize.go
  vendor/github.com/docker/distribution/reference/reference.go
  vendor/github.com/docker/distribution/reference/regexp.go
Labels: lgtm, ok-to-test, size/XL

#1445 adds git hub actions for linux CI
  .github/workflows/ci.yml
Labels: size/M

#1431 Enable to pass additional handler on pull for stargz-based remote snapshots
  pkg/config/config.go
  pkg/server/image_pull.go
Labels: ok-to-test, size/M

#1446 have moved these tests to github actions
  .travis.yml
Labels: size/M

#1450 add default scheme when mirrors no scheme
  pkg/server/image_pull.go
  pkg/server/image_pull_test.go
Labels: ok-to-test, size/M

#1451 split tests and some refactoring
  .github/workflows/ci.yml
Labels: size/M

#1436 Support for additional OCI annotations: 'container-name'
  pkg/annotations/annotations.go
  pkg/server/container_create.go
  pkg/server/container_create_test.go
  pkg/server/container_create_unix.go
  pkg/server/container_create_unix_test.go
  pkg/server/container_create_windows.go
  pkg/server/container_create_windows_test.go
Labels: ok-to-test, size/M

#1375 Update registry.md for auth config
  docs/registry.md
Labels: ok-to-test, size/XS

#1454 use project dco test locally
  Makefile
Labels: size/S

#1456 remove broken greetings github action
  .github/workflows/greetings.yml
Labels: size/S

#1457 Add improvement to docs
  README.md
  docs/crictl.md
  docs/testing.md
Labels: ok-to-test, size/S

#1464 move up to latest critools; add apparmor profile check
  hack/utils.sh
  pkg/server/container_create_unix.go
  pkg/server/container_create_unix_test.go
Labels: size/M

#1455 fix incomplete host device for PrivilegedWithoutHostDevices
  pkg/server/container_create_unix.go
Labels: lgtm, ok-to-test, size/XS

#1466 Pass chained layer digests to snapshotter for parallel snapshot preparation
  pkg/server/image_pull.go
Labels: lgtm, ok-to-test, size/S
