Repository containerd/cri, pull requests merged in 2020-08, with the labels that each got.

#1549 Bump Golang 1.13.14
  .appveyor.yml
  .github/workflows/ci.yml
  README.md
Labels: size/S

#1550 Bump containerd v1.4.0 rc.0
  vendor.conf
  vendor/github.com/containerd/containerd/container.go
  vendor/github.com/containerd/containerd/oci/spec_opts_unix.go
  vendor/github.com/containerd/containerd/remotes/docker/authorizer.go
  vendor/github.com/containerd/containerd/remotes/docker/fetcher.go
  vendor/github.com/containerd/containerd/remotes/docker/registry.go
  vendor/github.com/containerd/containerd/remotes/docker/resolver.go
  vendor/github.com/containerd/containerd/remotes/docker/scope.go
  vendor/github.com/containerd/containerd/services/tasks/local.go
  vendor/github.com/containerd/containerd/task.go
  vendor/github.com/containerd/containerd/vendor.conf
  vendor/github.com/containerd/containerd/version/version.go
  vendor/github.com/containerd/continuity/context.go
  vendor/github.com/containerd/continuity/devices/devices_unix.go
  vendor/github.com/containerd/continuity/digests.go
  vendor/github.com/containerd/continuity/driver/driver_windows.go
  vendor/github.com/containerd/continuity/fs/path.go
  vendor/github.com/containerd/continuity/go.mod
  vendor/github.com/containerd/continuity/groups_unix.go
  vendor/github.com/containerd/continuity/hardlinks.go
  vendor/github.com/containerd/continuity/hardlinks_unix.go
  vendor/github.com/containerd/continuity/manifest.go
  vendor/github.com/containerd/continuity/sysx/xattr_unsupported.go
  vendor/github.com/opencontainers/runc/go.mod
  vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/device.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/device_unix.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/device_windows.go
  vendor/github.com/opencontainers/runc/libcontainer/devices/devices.go
  vendor/github.com/opencontainers/runc/libcontainer/user/user.go
Labels: size/L

#1555 Bump Golang 1.13.15
  .appveyor.yml
  .github/workflows/ci.yml
  README.md
Labels: size/S

#1559 Prepare 1.4
  README.md
  vendor.conf
  vendor/github.com/containerd/containerd/cmd/containerd/command/oci-hook.go
  vendor/github.com/containerd/containerd/vendor.conf
  vendor/github.com/containerd/containerd/version/version.go
  vendor/github.com/opencontainers/runc/go.mod
  vendor/github.com/opencontainers/runc/libcontainer/configs/config.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/state.go
Labels: size/L

#1556 bump cni dependencies
  hack/install/install-cni-config.sh
  hack/install/install-cni.sh
  pkg/server/update_runtime_config_test.go
  vendor.conf
  vendor/github.com/containerd/go-cni/README.md
  vendor/github.com/containerd/go-cni/go.mod
  vendor/github.com/containernetworking/cni/README.md
  vendor/github.com/containernetworking/cni/libcni/api.go
  vendor/github.com/containernetworking/cni/libcni/conf.go
  vendor/github.com/containernetworking/cni/pkg/invoke/args.go
  vendor/github.com/containernetworking/cni/pkg/invoke/raw_exec.go
  vendor/github.com/containernetworking/cni/pkg/types/020/types.go
  vendor/github.com/containernetworking/cni/pkg/types/args.go
  vendor/github.com/containernetworking/cni/pkg/types/current/types.go
  vendor/github.com/containernetworking/cni/pkg/types/types.go
  vendor/github.com/containernetworking/cni/pkg/utils/utils.go
  vendor/github.com/containernetworking/plugins/README.md
  vendor/github.com/containernetworking/plugins/go.mod
  vendor/github.com/containernetworking/plugins/pkg/ns/README.md
  vendor/github.com/containernetworking/plugins/pkg/ns/ns_linux.go
Labels: cherrypick-needed, ok-to-test, size/XL

#1552 Add experimental NRI injection points
  pkg/server/container_start.go
  pkg/server/events.go
  pkg/server/opts.go
  pkg/server/sandbox_run.go
  vendor.conf
  vendor/github.com/containerd/nri/LICENSE
  vendor/github.com/containerd/nri/README.md
  vendor/github.com/containerd/nri/client.go
  vendor/github.com/containerd/nri/go.mod
  vendor/github.com/containerd/nri/types/v1/types.go
Labels: size/XL

#1560 [release/1.4] bump cni dependencies #1556
  hack/install/install-cni-config.sh
  hack/install/install-cni.sh
  pkg/server/update_runtime_config_test.go
  vendor.conf
  vendor/github.com/containerd/go-cni/README.md
  vendor/github.com/containerd/go-cni/go.mod
  vendor/github.com/containernetworking/cni/README.md
  vendor/github.com/containernetworking/cni/libcni/api.go
  vendor/github.com/containernetworking/cni/libcni/conf.go
  vendor/github.com/containernetworking/cni/pkg/invoke/args.go
  vendor/github.com/containernetworking/cni/pkg/invoke/raw_exec.go
  vendor/github.com/containernetworking/cni/pkg/types/020/types.go
  vendor/github.com/containernetworking/cni/pkg/types/args.go
  vendor/github.com/containernetworking/cni/pkg/types/current/types.go
  vendor/github.com/containernetworking/cni/pkg/types/types.go
  vendor/github.com/containernetworking/cni/pkg/utils/utils.go
  vendor/github.com/containernetworking/plugins/README.md
  vendor/github.com/containernetworking/plugins/go.mod
  vendor/github.com/containernetworking/plugins/pkg/ns/README.md
  vendor/github.com/containernetworking/plugins/pkg/ns/ns_linux.go
Labels: cherrypick, size/XL
