Repository containerd/cri, pull requests merged in 2020-01, with the labels that each got.

#1368 update for containerd vendor changes
  vendor.conf
  vendor/github.com/containerd/console/console.go
  vendor/github.com/containerd/console/console_linux.go
  vendor/github.com/containerd/console/console_unix.go
  vendor/github.com/containerd/console/console_windows.go
  vendor/github.com/containerd/console/go.mod
  vendor/github.com/containerd/containerd/runtime/v2/binary.go
  vendor/github.com/containerd/go-runc/command_linux.go
  vendor/github.com/containerd/go-runc/runc.go
  vendor/github.com/containerd/go-runc/utils.go
  vendor/github.com/cpuguy83/go-md2man/LICENSE.md
  vendor/github.com/cpuguy83/go-md2man/README.md
  vendor/github.com/cpuguy83/go-md2man/go.mod
  vendor/github.com/cpuguy83/go-md2man/md2man/md2man.go
  vendor/github.com/cpuguy83/go-md2man/md2man/roff.go
  vendor/github.com/modern-go/reflect2/type_map.go
  vendor/github.com/russross/blackfriday/LICENSE.txt
  vendor/github.com/russross/blackfriday/README.md
  vendor/github.com/russross/blackfriday/block.go
  vendor/github.com/russross/blackfriday/doc.go
  vendor/github.com/russross/blackfriday/go.mod
  vendor/github.com/russross/blackfriday/html.go
  vendor/github.com/russross/blackfriday/inline.go
  vendor/github.com/russross/blackfriday/latex.go
  vendor/github.com/russross/blackfriday/markdown.go
  vendor/github.com/russross/blackfriday/smartypants.go
  vendor/github.com/urfave/cli/README.md
  vendor/github.com/urfave/cli/app.go
  vendor/github.com/urfave/cli/category.go
  vendor/github.com/urfave/cli/cli.go
  vendor/github.com/urfave/cli/command.go
  vendor/github.com/urfave/cli/context.go
  vendor/github.com/urfave/cli/docs.go
  vendor/github.com/urfave/cli/fish.go
  vendor/github.com/urfave/cli/flag.go
  vendor/github.com/urfave/cli/flag_generated.go
  vendor/github.com/urfave/cli/funcs.go
  vendor/github.com/urfave/cli/go.mod
  vendor/github.com/urfave/cli/help.go
  vendor/github.com/urfave/cli/parse.go
  vendor/github.com/urfave/cli/sort.go
  vendor/github.com/urfave/cli/template.go
Labels: size/XXL

#1363 Validate and update the right config
  cri.go
Labels: cherrypick-needed, kind/bug, lgtm, size/XS

#1373 [release/1.3] Validate and update the right config
  cri.go
Labels: cherrypick, size/XS

#1374 Bump vendor containerd/containerd version
  vendor.conf
  vendor/github.com/containerd/containerd/api/services/snapshots/v1/snapshots.pb.go
  vendor/github.com/containerd/containerd/api/services/snapshots/v1/snapshots.proto
  vendor/github.com/containerd/containerd/archive/tar_unix.go
  vendor/github.com/containerd/containerd/filters/parser.go
  vendor/github.com/containerd/containerd/filters/scanner.go
  vendor/github.com/containerd/containerd/gc/gc.go
  vendor/github.com/containerd/containerd/metadata/snapshot.go
  vendor/github.com/containerd/containerd/mount/mount_linux.go
  vendor/github.com/containerd/containerd/platforms/platforms.go
  vendor/github.com/containerd/containerd/plugin/plugin_go18.go
  vendor/github.com/containerd/containerd/plugin/plugin_other.go
  vendor/github.com/containerd/containerd/services/content/contentserver/contentserver.go
  vendor/github.com/containerd/containerd/services/snapshots/service.go
  vendor/github.com/containerd/containerd/snapshots/proxy/proxy.go
  vendor/github.com/containerd/containerd/snapshots/snapshotter.go
  vendor/github.com/containerd/containerd/unpacker.go
  vendor/github.com/containerd/containerd/vendor.conf
Labels: lgtm, ok-to-test, size/XL

#1371 cgroup2: unshare cgroup namespace for containers
  pkg/server/container_create_unix.go
Labels: lgtm, size/S

#1383 Bump to opencontainers/runc new version - v1.0.0-rc10
  vendor.conf
  vendor/github.com/opencontainers/runc/README.md
  vendor/github.com/opencontainers/runc/vendor.conf
  vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
Labels: cherrypick-needed, ok-to-test, size/M

#1387 vendor: bump gopkg.in/yaml.v2 v2.2.8
  vendor.conf
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/gopkg.in/yaml.v2/yamlh.go
Labels: cherrypick-needed, ok-to-test, size/L

#1388 [release/1.2] vendor: bump gopkg.in/yaml.v2 v2.2.8
  vendor.conf
  vendor/gopkg.in/yaml.v2/LICENSE
  vendor/gopkg.in/yaml.v2/NOTICE
  vendor/gopkg.in/yaml.v2/README.md
  vendor/gopkg.in/yaml.v2/apic.go
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/emitterc.go
  vendor/gopkg.in/yaml.v2/encode.go
  vendor/gopkg.in/yaml.v2/go.mod
  vendor/gopkg.in/yaml.v2/parserc.go
  vendor/gopkg.in/yaml.v2/readerc.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/gopkg.in/yaml.v2/sorter.go
  vendor/gopkg.in/yaml.v2/writerc.go
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/gopkg.in/yaml.v2/yamlh.go
Labels: cherrypick, ok-to-test, size/XXL

#1386 [release/1.3 backport] update kubernetes dependency to v1.16.3
  vendor.conf
  vendor/github.com/json-iterator/go/iter.go
  vendor/github.com/json-iterator/go/iter_array.go
  vendor/github.com/json-iterator/go/iter_object.go
  vendor/github.com/json-iterator/go/iter_skip_sloppy.go
  vendor/github.com/json-iterator/go/reflect.go
  vendor/github.com/json-iterator/go/reflect_extension.go
  vendor/github.com/json-iterator/go/reflect_map.go
  vendor/github.com/json-iterator/go/reflect_marshaler.go
  vendor/github.com/json-iterator/go/reflect_struct_decoder.go
  vendor/github.com/modern-go/reflect2/type_map.go
  vendor/github.com/stretchr/testify/README.md
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/go.mod
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/golang.org/x/time/go.mod
  vendor/gopkg.in/inf.v0/dec.go
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/k8s.io/api/go.mod
  vendor/k8s.io/apimachinery/go.mod
  vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go
  vendor/k8s.io/apimachinery/pkg/util/intstr/intstr.go
  vendor/k8s.io/apimachinery/pkg/util/json/json.go
  vendor/k8s.io/apiserver/go.mod
  vendor/k8s.io/client-go/go.mod
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/kubernetes/go.mod
  vendor/k8s.io/utils/README.md
  vendor/k8s.io/utils/go.mod
Labels: cherrypick, ok-to-test, size/XXL

#1389 pick up fix for CVE-2019-19921 in opencontainers/selinux
  vendor.conf
  vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
Labels: cherrypick-needed, ok-to-test, size/M

#1392 [release/1.2] Sync vendors with containerd 1.2.11
  vendor.conf
  vendor/github.com/containerd/containerd/runtime/v1/linux/task.go
  vendor/github.com/containerd/containerd/runtime/v1/shim/service.go
  vendor/github.com/containerd/containerd/runtime/v2/shim.go
  vendor/github.com/containerd/containerd/services/tasks/local.go
  vendor/github.com/containerd/containerd/snapshots/storage/bolt.go
  vendor/github.com/containerd/containerd/vendor.conf
  vendor/github.com/containerd/containerd/version/version.go
  vendor/github.com/opencontainers/runc/libcontainer/apparmor/apparmor.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/config.go
  vendor/github.com/opencontainers/runc/libcontainer/seccomp/config.go
  vendor/github.com/opencontainers/runc/libcontainer/seccomp/seccomp_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/utils/cmsg.go
  vendor/github.com/opencontainers/runc/libcontainer/utils/utils.go
  vendor/github.com/opencontainers/runc/libcontainer/utils/utils_unix.go
  vendor/github.com/opencontainers/runc/vendor.conf
  vendor/google.golang.org/appengine/LICENSE
  vendor/google.golang.org/appengine/README.md
  vendor/google.golang.org/appengine/go.mod
  vendor/google.golang.org/appengine/internal/api.go
  vendor/google.golang.org/appengine/internal/api_classic.go
  vendor/google.golang.org/appengine/internal/api_common.go
  vendor/google.golang.org/appengine/internal/app_id.go
  vendor/google.golang.org/appengine/internal/base/api_base.pb.go
  vendor/google.golang.org/appengine/internal/base/api_base.proto
  vendor/google.golang.org/appengine/internal/datastore/datastore_v3.pb.go
  vendor/google.golang.org/appengine/internal/datastore/datastore_v3.proto
  vendor/google.golang.org/appengine/internal/identity.go
  vendor/google.golang.org/appengine/internal/identity_classic.go
  vendor/google.golang.org/appengine/internal/identity_flex.go
  vendor/google.golang.org/appengine/internal/identity_vm.go
  vendor/google.golang.org/appengine/internal/internal.go
  vendor/google.golang.org/appengine/internal/log/log_service.pb.go
  vendor/google.golang.org/appengine/internal/log/log_service.proto
  vendor/google.golang.org/appengine/internal/main.go
  vendor/google.golang.org/appengine/internal/main_common.go
  vendor/google.golang.org/appengine/internal/main_vm.go
  vendor/google.golang.org/appengine/internal/metadata.go
  vendor/google.golang.org/appengine/internal/net.go
  vendor/google.golang.org/appengine/internal/remote_api/remote_api.pb.go
  vendor/google.golang.org/appengine/internal/remote_api/remote_api.proto
  vendor/google.golang.org/appengine/internal/transaction.go
  vendor/google.golang.org/appengine/internal/urlfetch/urlfetch_service.pb.go
  vendor/google.golang.org/appengine/internal/urlfetch/urlfetch_service.proto
  vendor/google.golang.org/appengine/urlfetch/urlfetch.go
Labels: ok-to-test, size/XXL

#1390 [release/1.3] update kubernetes and its dependencies to v1.16.6
  vendor.conf
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/k8s.io/api/go.mod
  vendor/k8s.io/apimachinery/go.mod
  vendor/k8s.io/apiserver/go.mod
  vendor/k8s.io/client-go/go.mod
  vendor/k8s.io/cri-api/go.mod
  vendor/k8s.io/kubernetes/go.mod
Labels: cherrypick-needed, ok-to-test, size/L
