Repository containerd/cri, pull requests merged in 2020-07, with the labels that each got.

#1520 CI: run apt-get update befor apt-get install
  .github/workflows/ci.yml
Labels: size/XS

#1519 config: TolerateMissingHugePagesCgroupController -> TolerateMissingHugetlbController
  docs/config.md
  pkg/config/config.go
  pkg/config/config_unix.go
  pkg/containerd/opts/spec_unix.go
  pkg/server/container_create_unix.go
  pkg/server/container_update_resources_unix.go
Labels: size/M

#1524 set dco check to verbose
  .github/workflows/ci.yml
Labels: size/XS

#1525 Forcibly remove sandbox container
  hack/utils.sh
  integration/sandbox_clean_remove_test.go
  pkg/server/container_remove.go
  pkg/server/sandbox_remove.go
  pkg/server/sandbox_stop.go
Labels: size/M

#1440 Containerd-Cri with supports multi-architectures
  hack/release.sh
Labels: ok-to-test, size/S

#1530 Fix doc for runtime specific options
  docs/config.md
Labels: needs-ok-to-test, size/M

#1531 show runc options tag
  pkg/config/config_unix.go
Labels: size/XS

#1532 Update to latest Windows SandboxImage
  pkg/config/config_windows.go
Labels: ok-to-test, size/XS

#1529 allow disabling hugepages
  pkg/config/config.go
  pkg/config/config_unix.go
  pkg/containerd/opts/spec_unix.go
  pkg/server/container_create_unix.go
  pkg/server/container_update_resources_unix.go
  pkg/server/container_update_resources_unix_test.go
Labels: size/M

#1539 switching to windows-2016.. latest is breaking due to wsl conflict with bash
  .github/workflows/ci.yml
Labels: size/XS

#1535 Update doc cri plugin convention
  docs/decryption.md
Labels: ok-to-test, size/XS

#1534 Update selinux pkg and allow category range to be set in config
  docs/config.md
  pkg/config/config.go
  pkg/config/config_unix.go
  pkg/server/service_unix.go
  vendor.conf
  vendor/github.com/opencontainers/selinux/README.md
  vendor/github.com/opencontainers/selinux/go-selinux/doc.go
  vendor/github.com/opencontainers/selinux/go-selinux/label/label.go
  vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
  vendor/github.com/opencontainers/selinux/go-selinux/label/label_stub.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
  vendor/github.com/opencontainers/selinux/go.mod
  vendor/github.com/opencontainers/selinux/pkg/pwalk/pwalk.go
  vendor/github.com/willf/bitset/LICENSE
  vendor/github.com/willf/bitset/README.md
  vendor/github.com/willf/bitset/bitset.go
  vendor/github.com/willf/bitset/popcnt.go
  vendor/github.com/willf/bitset/popcnt_19.go
  vendor/github.com/willf/bitset/popcnt_amd64.go
  vendor/github.com/willf/bitset/popcnt_amd64.s
  vendor/github.com/willf/bitset/popcnt_generic.go
  vendor/github.com/willf/bitset/trailing_zeros_18.go
  vendor/github.com/willf/bitset/trailing_zeros_19.go
Labels: size/XXL

#1542 Update config syntax in registry.md (GCR example)
  docs/registry.md
Labels: ok-to-test, size/XS

#1545 Add description about `disable_snapshot_annotations` to configuration doc
  docs/config.md
Labels: ok-to-test, size/XS

#1547 adds support for pod id lookup for filter
  pkg/server/container_list.go
Labels: size/S

#1548 remove libseccomp cgo dependency
  pkg/seccomp/fixtures/proc_self_status
  pkg/seccomp/seccomp_linux.go
  pkg/seccomp/seccomp_linux_test.go
  pkg/seccomp/seccomp_unsupported.go
  pkg/server/helpers_unix.go
  vendor.conf
  vendor/github.com/opencontainers/runc/libcontainer/seccomp/config.go
  vendor/github.com/opencontainers/runc/libcontainer/seccomp/seccomp_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/seccomp/seccomp_unsupported.go
  vendor/github.com/seccomp/libseccomp-golang/LICENSE
  vendor/github.com/seccomp/libseccomp-golang/README
  vendor/github.com/seccomp/libseccomp-golang/seccomp.go
  vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go
Labels: cherrypick-needed, size/XXL
