Repository containerd/cri, pull requests merged in 2020-03, with the labels that each got.

#1411 Reformat vendor.conf: use columns, pin by git-sha, and sort alphabetically
  vendor.conf
Labels: size/L

#1412 update to golang 1.13.8
  .appveyor.yml
  .travis.yml
  README.md
Labels: size/XS

#1415 cgroup2: do not unshare cgroup namespace for privileged
  pkg/server/container_create_unix.go
Labels: lgtm, size/XS

#1417 add golang 1.14 to prepare for move
  .travis.yml
Labels: size/XS

#1382 Add correct paths for cri's systemd config files in CentOS.
  contrib/ansible/cri-containerd.yaml
Labels: lgtm, ok-to-test, size/S

#1420 backport release/1.3: Fix integration test for golang 1.13
  integration/main_test.go
Labels: cherrypicked, lgtm, ok-to-test, size/XS

#1423 Add version numbers for newly tagged repos
  vendor.conf
Labels: ok-to-test, size/XS

#1422 Bump golang to v1.13.9 and v1.14.1
  .appveyor.yml
  .travis.yml
  README.md
Labels: ok-to-test, size/S

#1426 vendor: update kubernetes v1.18.0
  vendor.conf
  vendor/k8s.io/api/core/v1/generated.pb.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/core/v1/well_known_taints.go
  vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go
  vendor/k8s.io/api/go.mod
  vendor/k8s.io/apimachinery/go.mod
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/helpers.go
  vendor/k8s.io/apimachinery/pkg/util/errors/errors.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/apimachinery/pkg/util/validation/validation.go
  vendor/k8s.io/apimachinery/pkg/util/wait/doc.go
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go
  vendor/k8s.io/apiserver/go.mod
  vendor/k8s.io/client-go/go.mod
  vendor/k8s.io/client-go/rest/request.go
  vendor/k8s.io/client-go/tools/clientcmd/api/types.go
  vendor/k8s.io/client-go/tools/metrics/metrics.go
  vendor/k8s.io/client-go/transport/cache.go
  vendor/k8s.io/client-go/transport/cert_rotation.go
  vendor/k8s.io/client-go/transport/config.go
  vendor/k8s.io/client-go/transport/transport.go
  vendor/k8s.io/client-go/util/workqueue/default_rate_limiters.go
  vendor/k8s.io/client-go/util/workqueue/delaying_queue.go
  vendor/k8s.io/client-go/util/workqueue/doc.go
  vendor/k8s.io/client-go/util/workqueue/metrics.go
  vendor/k8s.io/client-go/util/workqueue/parallelizer.go
  vendor/k8s.io/client-go/util/workqueue/queue.go
  vendor/k8s.io/client-go/util/workqueue/rate_limiting_queue.go
  vendor/k8s.io/kubernetes/go.mod
  vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  vendor/k8s.io/kubernetes/pkg/apis/core/zz_generated.deepcopy.go
  vendor/k8s.io/kubernetes/pkg/util/bandwidth/linux.go
Labels: ok-to-test, size/XXL

#1418 Fix goroutine leak when exec/attach
  pkg/server/container_attach.go
  pkg/server/container_execsync.go
  pkg/server/streaming.go
Labels: lgtm, ok-to-test, size/S
