Repository containerd/cri, pull requests merged in 2020-02, with the labels that each got.

#1394 [release/1.3 backport] vendor: bump gopkg.in/yaml.v2 v2.2.8
  vendor.conf
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/gopkg.in/yaml.v2/yamlh.go
Labels: size/L

#1384 Fix store error serialization to gRPC status codes
  pkg/store/errors.go
  pkg/store/errors_test.go
Labels: size/M

#1332 update cri-plugin to parse hugepages limit
  pkg/containerd/opts/spec_unix.go
  vendor.conf
  vendor/k8s.io/api/core/v1/resource.go
  vendor/k8s.io/api/go.mod
  vendor/k8s.io/apimachinery/go.mod
  vendor/k8s.io/apimachinery/pkg/apis/meta/internalversion/register.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/conversion.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/register.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1beta1/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1beta1/generated.proto
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1beta1/register.go
  vendor/k8s.io/apimachinery/pkg/conversion/converter.go
  vendor/k8s.io/apimachinery/pkg/runtime/conversion.go
  vendor/k8s.io/apimachinery/pkg/runtime/embedded.go
  vendor/k8s.io/apimachinery/pkg/runtime/scheme.go
  vendor/k8s.io/apimachinery/pkg/util/clock/clock.go
  vendor/k8s.io/apimachinery/pkg/watch/watch.go
  vendor/k8s.io/apiserver/go.mod
  vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go
  vendor/k8s.io/client-go/README.md
  vendor/k8s.io/client-go/go.mod
  vendor/k8s.io/client-go/plugin/pkg/client/auth/exec/exec.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/exec/metrics.go
  vendor/k8s.io/client-go/rest/request.go
  vendor/k8s.io/client-go/tools/metrics/metrics.go
  vendor/k8s.io/cri-api/go.mod
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.pb.go
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.proto
  vendor/k8s.io/kubernetes/go.mod
  vendor/k8s.io/kubernetes/pkg/apis/core/resource.go
Labels: lgtm, ok-to-test, size/XXL

#1402 vendor: golang.org/x/crypto 1d94cc7ab1c630336ab82ccb9c9cda72a875c382
  vendor.conf
  vendor/golang.org/x/crypto/curve25519/const_amd64.h
  vendor/golang.org/x/crypto/curve25519/const_amd64.s
  vendor/golang.org/x/crypto/curve25519/cswap_amd64.s
  vendor/golang.org/x/crypto/curve25519/curve25519.go
  vendor/golang.org/x/crypto/curve25519/doc.go
  vendor/golang.org/x/crypto/curve25519/freeze_amd64.s
  vendor/golang.org/x/crypto/curve25519/ladderstep_amd64.s
  vendor/golang.org/x/crypto/curve25519/mont25519_amd64.go
  vendor/golang.org/x/crypto/curve25519/mul_amd64.s
  vendor/golang.org/x/crypto/curve25519/square_amd64.s
  vendor/golang.org/x/crypto/go.mod
  vendor/golang.org/x/crypto/ssh/terminal/terminal.go
  vendor/golang.org/x/crypto/ssh/terminal/util_windows.go
Labels: cherrypick-needed, lgtm, size/XXL

#1399 move to v3.2 for the pause image
  contrib/ansible/cri-containerd.yaml
  docs/config.md
  docs/crictl.md
  integration/main_test.go
  pkg/config/config_unix.go
Labels: lgtm, size/M

#1407 Update to a released version of opencontainers/selinux (1.3.3)
  vendor.conf
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
  vendor/github.com/opencontainers/selinux/go-selinux/xattrs.go
  vendor/github.com/opencontainers/selinux/go.mod
Labels: ok-to-test, size/L
