Repository containerd/cri, pull requests merged in 2020-06, with the labels that each got.

#1501 Tolerate missing HugeTLB cgroups controller
  pkg/config/config.go
  pkg/config/config_unix.go
  pkg/containerd/opts/spec_unix.go
  pkg/server/container_create_unix.go
  pkg/server/container_update_resources_unix.go
  pkg/server/container_update_resources_unix_test.go
Labels: cherrypick-needed, kind/bug, kind/config, kind/docs, priority/P0, size/L

#1502 move up to latest cri-tools - pick up nginx fix
  hack/utils.sh
Labels: size/XS

#1506 Add config for registry http headers
  docs/config.md
  pkg/config/config.go
  pkg/server/image_pull.go
Labels: size/XS

#1499 Fix typo
  docs/registry.md
Labels: ok-to-test, size/XS

#1505 Add GMSA credential spec passing
  pkg/containerd/opts/spec_windows.go
  pkg/server/container_create_windows.go
  pkg/server/container_create_windows_test.go
Labels: ok-to-test, size/M

#1504 Add option for ignoring volumes defined in images
  docs/config.md
  pkg/config/config.go
  pkg/config/config_unix.go
  pkg/config/config_windows.go
  pkg/server/container_create.go
Labels: ok-to-test, size/S

#1508 Remove the protocol filter from the HostPort management
  pkg/server/sandbox_run.go
  pkg/server/sandbox_run_test.go
Labels: ok-to-test, size/S

#1510 bump selinux dep
  vendor.conf
  vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
Labels: size/S

#1515 Bump Golang 1.13.12
  .appveyor.yml
  .github/workflows/ci.yml
  README.md
Labels: size/S

#1517 hard set kubernetes version not in vendor.conf anymore
  hack/test-e2e-node.sh
  hack/utils.sh
  pkg/server/image_pull.go
Labels: size/S

#1511 Support named pipe mounts for Windows containers
  pkg/containerd/opts/spec_windows.go
  pkg/server/container_create_windows_test.go
Labels: ok-to-test, size/M

#1513 Change "failed to stop sandbox" error message to use state name instead of numeric value
  pkg/store/sandbox/status.go
  pkg/store/sandbox/status_test.go
Labels: ok-to-test, size/S
