Repository containerd/cri, pull requests merged in 2020-10, with the labels that each got.

#1591 Doc (registry): Update to the image registry doc
  docs/registry.md
Labels: needs-ok-to-test, size/M

#1592 Align lint with containerd
  .golangci.yml
  integration/addition_gids_test.go
  integration/container_log_test.go
  integration/container_restart_test.go
  integration/container_stats_test.go
  integration/container_stop_test.go
  integration/container_update_resources_test.go
  integration/container_without_image_ref_test.go
  integration/containerd_image_test.go
  integration/duplicate_name_test.go
  integration/image_load_test.go
  integration/imagefs_info_test.go
  integration/main_test.go
  integration/no_metadata_test.go
  integration/pod_dualstack_test.go
  integration/pod_hostname_test.go
  integration/remote/remote_image.go
  integration/remote/remote_runtime.go
  integration/restart_test.go
  integration/runtime_handler_test.go
  integration/sandbox_clean_remove_test.go
  integration/truncindex_test.go
  integration/volume_copy_up_test.go
  pkg/api/runtimeoptions/v1/api.proto
  pkg/server/container_create_unix_test.go
  pkg/server/image_pull_test.go
  pkg/store/sandbox/status_test.go
Labels: size/L

#1593 Add missing sandbox labels when invoking nri
  pkg/server/container_start.go
Labels: needs-ok-to-test, size/XS

#1597 update README to clarify the current status of this repo
  README.md
Labels: cherrypick-needed, kind/docs, size/S

#1599 [release/1.4] update README to clarify the current status of this repo
  README.md
Labels: size/S
