Repository containerd/cri, pull requests merged in 2020-05, with the labels that each got.

#1465 Clarify that plugin names are long in version = 2
  docs/config.md
  docs/registry.md
Labels: ok-to-test, size/XS

#1468 RunPodSandbox: destroy network if fails or invalid
  pkg/server/sandbox_run.go
Labels: size/S

#1470 Get rid of socat for port forwarding
  .github/workflows/ci.yml
  README.md
  contrib/ansible/tasks/bootstrap_centos.yaml
  contrib/ansible/tasks/bootstrap_ubuntu.yaml
  pkg/server/sandbox_portforward_unix.go
Labels: ok-to-test, size/L

#1474 vendor: kubernetes v1.18.2
  vendor.conf
  vendor/k8s.io/api/go.mod
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go
  vendor/k8s.io/apiserver/go.mod
  vendor/k8s.io/client-go/go.mod
  vendor/k8s.io/client-go/rest/request.go
Labels: size/M

#1475 newTransport(): remove deprecated DualStack option
  pkg/server/image_pull.go
Labels: size/XS

#1449 removes the error when tls is configured for https but http is tried first
  pkg/server/image_pull.go
Labels: size/XS

#1469 Remove dependency on libcontainer/system
  pkg/server/service_unix.go
  vendor/github.com/opencontainers/runc/libcontainer/system/linux.go
  vendor/github.com/opencontainers/runc/libcontainer/system/proc.go
  vendor/github.com/opencontainers/runc/libcontainer/system/syscall_linux_32.go
  vendor/github.com/opencontainers/runc/libcontainer/system/syscall_linux_64.go
  vendor/github.com/opencontainers/runc/libcontainer/system/sysconfig.go
  vendor/github.com/opencontainers/runc/libcontainer/system/sysconfig_notcgo.go
  vendor/github.com/opencontainers/runc/libcontainer/system/unsupported.go
  vendor/github.com/opencontainers/runc/libcontainer/system/xattrs_linux.go
Labels: size/L

#1429 Create etcd user in cloud init.
  cluster/gce/cloud-init/master.yaml
Labels: size/XS

#1472 Add config flag to default empty seccomp profile
  docs/config.md
  pkg/config/config.go
  pkg/server/container_create_unix.go
  pkg/server/container_create_unix_test.go
  pkg/server/sandbox_run_unix.go
Labels: lgtm, ok-to-test, size/M

#1476 Use digestset from go-digest
  pkg/store/image/image.go
  pkg/store/image/image_test.go
  vendor.conf
  vendor/github.com/docker/distribution/LICENSE
  vendor/github.com/docker/distribution/README.md
  vendor/github.com/docker/distribution/vendor.conf
  vendor/github.com/opencontainers/go-digest/LICENSE
  vendor/github.com/opencontainers/go-digest/README.md
  vendor/github.com/opencontainers/go-digest/algorithm.go
  vendor/github.com/opencontainers/go-digest/digest.go
  vendor/github.com/opencontainers/go-digest/digester.go
  vendor/github.com/opencontainers/go-digest/digestset/set.go
  vendor/github.com/opencontainers/go-digest/doc.go
  vendor/github.com/opencontainers/go-digest/go.mod
  vendor/github.com/opencontainers/go-digest/verifiers.go
Labels: size/L

#1477 Increase port-forward timeout to 1s to fix e2e test
  pkg/server/sandbox_portforward_unix.go
Labels: ok-to-test, size/XS

#1480 removing boilerplate test already replaced by project boiler check
  .github/workflows/ci.yml
  Makefile
  docs/testing.md
  hack/boilerplate/.gitignore
  hack/boilerplate/BUILD
  hack/boilerplate/boilerplate
  hack/boilerplate/boilerplate.Dockerfile.txt
  hack/boilerplate/boilerplate.Makefile.txt
  hack/boilerplate/boilerplate.py
  hack/boilerplate/boilerplate.py.txt
  hack/boilerplate/boilerplate.sh.txt
  hack/boilerplate/boilerplate_test.py
  hack/boilerplate/test/fail.go
  hack/boilerplate/test/fail.py
  hack/boilerplate/test/pass.go
  hack/boilerplate/test/pass.py
  hack/update-proto.sh
  hack/verify-boilerplate.sh
Labels: size/L

#1483 vendor: containerd/go-cni 0553354f0046ccd41a02e724826040491a3d8998
  vendor.conf
  vendor/github.com/containerd/go-cni/README.md
  vendor/github.com/containerd/go-cni/errors.go
  vendor/github.com/containerd/go-cni/go.mod
  vendor/github.com/containerd/go-cni/opts.go
  vendor/github.com/containerd/go-cni/vendor.conf
Labels: size/M

#1484 vendor: containerd/containerd v1.4.0-beta.0
  vendor.conf
  vendor/github.com/containerd/containerd/README.md
  vendor/github.com/containerd/containerd/archive/tar.go
  vendor/github.com/containerd/containerd/container_opts.go
  vendor/github.com/containerd/containerd/errdefs/errors.go
  vendor/github.com/containerd/containerd/images/handlers.go
  vendor/github.com/containerd/containerd/pkg/process/utils.go
  vendor/github.com/containerd/containerd/plugin/plugin.go
  vendor/github.com/containerd/containerd/remotes/docker/pusher.go
  vendor/github.com/containerd/containerd/remotes/docker/resolver.go
  vendor/github.com/containerd/containerd/runtime/v1/linux/process.go
  vendor/github.com/containerd/containerd/runtime/v1/linux/task.go
  vendor/github.com/containerd/containerd/runtime/v2/process.go
  vendor/github.com/containerd/containerd/runtime/v2/shim.go
  vendor/github.com/containerd/containerd/runtime/v2/shim_windows.go
  vendor/github.com/containerd/containerd/unpacker.go
  vendor/github.com/containerd/containerd/vendor.conf
  vendor/github.com/containerd/containerd/version/version.go
  vendor/github.com/containerd/continuity/driver/driver.go
  vendor/github.com/containerd/continuity/driver/driver_unix.go
  vendor/github.com/containerd/continuity/driver/driver_windows.go
  vendor/github.com/containerd/continuity/fs/copy_unix.go
  vendor/github.com/containerd/continuity/fs/stat_darwinfreebsd.go
  vendor/github.com/containerd/continuity/fs/stat_linuxopenbsd.go
  vendor/github.com/containerd/continuity/syscallx/syscall_unix.go
  vendor/github.com/containerd/continuity/syscallx/syscall_windows.go
  vendor/github.com/containerd/continuity/sysx/file_posix.go
  vendor/github.com/containerd/continuity/sysx/nodata_unix.go
  vendor/github.com/containerd/continuity/sysx/xattr.go
  vendor/github.com/containerd/fifo/errors.go
  vendor/github.com/containerd/fifo/fifo.go
  vendor/github.com/containerd/fifo/go.mod
  vendor/github.com/containerd/fifo/handle_linux.go
  vendor/github.com/containerd/fifo/raw.go
  vendor/github.com/containerd/go-runc/go.mod
  vendor/github.com/containerd/go-runc/runc.go
  vendor/github.com/modern-go/reflect2/type_map.go
Labels: size/XL

#1485 vendor.conf: back to using tags
  vendor.conf
Labels: size/L

#1486 Bump Golang 1.13.11
  .appveyor.yml
  .github/workflows/ci.yml
  README.md
Labels: size/S

#1489 no longer need to skip /test header scan due to symlink
  .github/workflows/ci.yml
Labels: size/XS

#1491 vendor: opencontainers/selinux v1.5.2
  vendor.conf
  vendor/github.com/opencontainers/selinux/go-selinux/label/label.go
  vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
  vendor/github.com/opencontainers/selinux/go-selinux/label/label_stub.go
Labels: size/M

#1487 Add SELinux Support for CRI
  Makefile
  hack/install/install-runc.sh
  hack/test-utils.sh
  hack/utils.sh
  pkg/containerd/opts/spec_unix.go
  pkg/server/container_create.go
  pkg/server/container_create_unix.go
  pkg/server/container_create_unix_test.go
  pkg/server/helpers_selinux_test.go
  pkg/server/helpers_unix.go
  pkg/server/sandbox_run.go
  pkg/server/sandbox_run_unix.go
  pkg/server/sandbox_run_unix_test.go
  pkg/server/service.go
  pkg/server/service_test.go
  pkg/store/container/container.go
  pkg/store/container/container_test.go
  pkg/store/container/metadata.go
  pkg/store/label/label.go
  pkg/store/label/label_test.go
  pkg/store/sandbox/metadata.go
  pkg/store/sandbox/sandbox.go
  pkg/store/sandbox/sandbox_test.go
Labels: size/XL

#1494 docs moved
  README.md
Labels: ok-to-test, size/XS

#1495 Use go-cni tag
  vendor.conf
Labels: size/XS

#1496 add support for setting CRITOOL_VERSION
  hack/utils.sh
Labels: size/XS

#1497 would like to have the commit sha in the log file names
  .github/workflows/ci.yml
Labels: size/XS

#1490 add a registry auth tutorial
  docs/registry.md
Labels: size/M

#1498 Specify base OCI runtime spec
  docs/config.md
  pkg/config/config.go
  pkg/server/container_create.go
  pkg/server/container_create_test.go
  pkg/server/container_create_unix.go
  pkg/server/container_create_unix_test.go
  pkg/server/container_create_windows.go
  pkg/server/sandbox_run_unix.go
  pkg/server/sandbox_run_windows.go
  pkg/server/service.go
  pkg/server/service_test.go
Labels: size/L
