Repository containerd/cri, pull requests merged in 2020-11, with the labels that each got.

#1602 Disable experimental feature in default config
  pkg/config/config_unix.go
Labels: size/XS

#1607 [release/1.4] gha: replace uses of deprecated "set-env", "add-path"
  .github/workflows/ci.yml
Labels: size/S

#1606 [release/1.4] vendor: kubernetes v1.19.4
  README.md
  vendor.conf
  vendor/k8s.io/api/go.mod
  vendor/k8s.io/apiserver/go.mod
  vendor/k8s.io/client-go/go.mod
  vendor/k8s.io/client-go/transport/cache.go
  vendor/k8s.io/component-base/go.mod
Labels: size/L

#1609 [release/1.4] Add manifest digest annotation for snapshotters
  pkg/server/image_pull.go
  pkg/server/image_pull_test.go
Labels: needs-ok-to-test, size/L

#1605 [release/1.4 backport] selinux: relabel /dev/shm
  pkg/server/container_create_unix.go
  pkg/server/container_create_unix_test.go
Labels: ok-to-test, size/S

#1611 [release/1.3] Fix golangci-lint installation
  Makefile
Labels: size/XS

#1604 [release/1.3] enable test-integration target to specify runtime
  hack/test-utils.sh
Labels: size/S

#1603 [release/1.4] backport: ci: run test-integration target for all runtimes
  .github/workflows/ci.yml
  hack/test-utils.sh
Labels: size/M

#1600 [release/1.4 backport] fix: always set unknown to false when handling exit event
  pkg/server/events.go
Labels: ok-to-test, size/S

#1608 [release/1.4] update Go 1.15.5 (to match containerd)
  .appveyor.yml
  .github/workflows/ci.yml
  README.md
  hack/utils.sh
Labels: size/S
